- platform: broadlink
  host: 192.168.86.106
  mac: 'C8:F7:42:16:AD:21'
  type: rm_mini
  timeout: 15
  switches:
    livingroomtv:
      friendly_name: "Hisense TV"
      command_on: 'JgBgAAABKJEUERQRFBAVEBQRFBAUERQRFDUUNhQ1FDUUNhQ1FBEUNRQ2FBAUNhQ1FBEUERMRFBEUERQ1FBEUEBQ2FDUUNRQ2FAAFOQABKEgUAAw+AAEoSBQADD4AAShJFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABKJEUERQRFBAVEBQRFBAUERQRFDUUNhQ1FDUUNhQ1FBEUNRQ2FBAUNhQ1FBEUERMRFBEUERQ1FBEUEBQ2FDUUNRQ2FAAFOQABKEgUAAw+AAEoSBQADD4AAShJFAANBQAAAAAAAAAA'
