- platform: template
  switches:
    livingroom_light_group:
      icon_template: mdi:sofa
      friendly_name: "Livingroom"
      value_template: "{{ not is_state('input_select.livingroom_preset', 'TurnOff') }}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.livingroom_preset
          option: "Normal"
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.livingroom_preset
          option: "TurnOff"
    kitchen_light_group:
      icon_template: mdi:fridge
      friendly_name: "Kitchen"
      value_template: "{{ states('light.kitchen_light_group') }}"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.kitchen_light_group
            brightness_pct: 100
            transition: 1
            color_temp: 370
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.kitchen_light_group
            transition: 1
    backroom_light_group:
      icon_template: mdi:castle
      friendly_name: "Backroom"
      value_template: "{{ states('light.backroom_light_group') }}"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.backroom_light_group
            brightness_pct: 100
            color_temp: 370
            white_value: 255
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.backroom_light_group
            transition: 1
    craftroom_light:
      icon_template: mdi:content-cut
      friendly_name: "Craft"
      value_template: "{{ states('light.craft_room') }}"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.craft_room
            brightness_pct: 100
            color_temp: 370
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.craft_room
            transition: 1
    bedroom_light_group:
      value_template: "{{ states('light.bedroom_light_group') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Bedroom"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.bedroom_light_group
            brightness_pct: 100
            color_temp: 370
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.bedroom_light_group
            transition: 1
    lucas_bedroom_light:
      value_template: "{{ states('light.lucas') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Lucas Bedroom"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.lucas
            brightness_pct: 1
            white_value: 255
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.lucas
            transition: 1
    xander_bedroom_light:
      value_template: "{{ states('light.xander_bedroom_light_light') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Xander Bedroom"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.xander_bedroom_light_light
            brightness_pct: 100
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.xander_bedroom_light_light
            transition: 1
    entry_lights:
      value_template: "{{ states('group.entry_lights') }}"
      icon_template: mdi:door
      friendly_name: "Entry"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.entry_lights
            brightness_pct: 100
            color_name: white
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: group.entry_lights
            transition: 1
    hall_lights:
      value_template: "{{ states('group.hall_lights') }}"
      friendly_name: "Hall"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.hall_lights
            brightness_pct: 100
            color_name: white
            transition: 1
      turn_off:
        service: light.turn_off
        data:
            entity_id: group.hall_lights
            transition: 1
    front_lights:
      value_template: "{{ states('light.sensor_light') }}"
      icon_template: mdi:car
      friendly_name: "Front"
      turn_on:
        service: light.turn_on
        data:
            entity_id: light.sensor_light
            brightness_pct: 100
      turn_off:
        service: light.turn_off
        data:
            entity_id: light.sensor_light
