- platform: template
  switches:
    backroom_ptz_up:
      value_template: "{{ False }}"
      turn_off:
      turn_on:
        - service: script.backroom_ptz_up
    backroom_ptz_down:
      value_template: "{{ False }}"
      turn_off:
      turn_on:
        - service: script.backroom_ptz_down
    backroom_ptz_left:
      value_template: "{{ False }}"
      turn_off:
      turn_on:
        - service: script.backroom_ptz_left
    backroom_ptz_right:
      value_template: "{{ False }}"
      turn_off:
      turn_on:
        - service: script.backroom_ptz_right
