- platform: template
  switches:
    livingroom_lights:
      icon_template: mdi:sofa
      friendly_name: "Livingroom"
      value_template: "{{ not is_state('input_select.livingroom_preset', 'TurnOff') }}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.livingroom_preset
          option: "Normal"
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.livingroom_preset
          option: "TurnOff"
    kitchen_lights:
      icon_template: mdi:fridge
      friendly_name: "Kitchen"
      value_template: "{{ states('group.kitchen_lights') }}"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.kitchen_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.kitchen_lights
    backroom_lights:
      icon_template: mdi:castle
      friendly_name: "Backroom"
      value_template: "{{ states('group.backroom_lights') }}"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.backroom_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.backroom_lights
    craftroom_lights:
      icon_template: mdi:content-cut
      friendly_name: "Craft"
      value_template: "{{ states('group.craftroom_lights') }}"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.craftroom_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.craftroom_lights
    office_lights:
      value_template: "{{ states('group.office_lights') }}"
      icon_template: mdi:desktop-classic
      friendly_name: "Office"
      turn_on:
        - service: light.turn_on
          data:
            entity_id: group.office_lights
            brightness_pct: 100
        - service: homeassistant.turn_on
          data:
            entity_id: group.office_lights
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.office_lights
    bedroom_lights:
      value_template: "{{ states('group.bedroom_lights') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Bedroom"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.bedroom_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.bedroom_lights
    lucas_bedroom_lights:
      value_template: "{{ states('group.lucas_bedroom_lights') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Lucas Bedroom"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.lucas_bedroom_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.lucas_bedroom_lights
    xander_bedroom_lights:
      value_template: "{{ states('group.xander_bedroom_lights') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Xander Bedroom"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.xander_bedroom_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.xander_bedroom_lights
    entry_lights:
      value_template: "{{ states('group.entry_lights') }}"
      icon_template: mdi:door
      friendly_name: "Entry"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.entry_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.entry_lights
    hall_lights:
      value_template: "{{ states('group.hall_lights') }}"
      friendly_name: "Hall"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.hall_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.hall_lights
    front_lights:
      value_template: "{{ states('group.front_lights') }}"
      icon_template: mdi:car
      friendly_name: "Front"
      turn_on:
        service: light.turn_on
        data:
            entity_id: group.front_lights
            brightness_pct: 100
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.front_lights
