- id: '1597056191228'
  alias: Lucas light back off
  description: ''
  trigger:
  - entity_id: light.lucas_lights
    for: '"00:05:00"'
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: '21:00'
    before: '6:00'
    condition: time
  action:
  - data: {}
    entity_id: light.lucas_lights
    service: light.turn_off
  mode: restart
- id: '1604523377433'
  alias: Android - Basic notification
  description: ''
  trigger:
  - platform: state
    entity_id: light.office_strip
  condition: []
  action:
  - service: notify.mobile_app_chrisphone
    data:
      title: Lights
      message: 'The current temp is: {{states(''sensor.office_temperature'')}}'
      data:
        actions:
        - action: LIGHTS_RAINBOW
          title: Rainbow time
        - action: LIGHTS_TWINKLE
          title: Twinkle time
        - action: LIGHTS_OFF
          title: 'Off'
  mode: single
- id: '1604525361961'
  alias: Android - Office rainbow
  description: ''
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: LIGHTS_RAINBOW
  condition: []
  action:
  - service: light.turn_on
    data:
      entity_id: light.office_strip
      effect: Rainbow
  mode: single
- id: '1607223896706'
  alias: Christmas Lights On
  description: ''
  trigger:
  - platform: time
    at: '18:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.bedroom_plug_bottom
  mode: single
- id: '1607223951158'
  alias: Christmas Lights off
  description: ''
  trigger:
  - platform: time
    at: '23:59'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.bedroom_plug_bottom
  mode: single
