- platform: mjpeg
  name: backroom
  mjpeg_url: http://192.168.86.41/media?action=stream&user=admin&pwd=
  still_image_url: http://192.168.86.41/snapshot.cgi?user=admin&pwd=
  verify_ssl: false
- platform: generic
  stream_source: rtsp://192.168.86.56:554/
  still_image_url: http://192.168.86.56:554/snapshot
  name: camera2
- platform: mjpeg
  name: livingcam
  still_image_url: http://192.168.86.61/image.jpg
  mjpeg_url: http://192.168.86.61/MJPEG.CGI
- platform: onvif
  name: camera3
  host: 192.168.86.74
  username: admin
  password: admin
  port: 10080
