- platform: mjpeg
  name: backroom
  mjpeg_url: http://192.168.86.41/media?action=stream&user=admin&pwd=
  still_image_url: http://192.168.86.41/snapshot.cgi?user=admin&pwd=
  verify_ssl: false
- platform: ffmpeg
  input: rtsp://192.168.86.56:554/
  name: camera2
- platform: mjpeg
  name: livingcam
  still_image_url: http://192.168.86.61/image.jpg
  mjpeg_url: http://192.168.86.61/MJPEG.CGI
