- platform: generic
  name: minicam
  stream_source: http://192.168.86.105/videostream.asf?user=admin&pwd=&resolution=32
  still_image_url: http://192.168.86.105/media?action=snapshot&user=admin&pwd=
- platform: generic
  stream_source: rtsp://192.168.86.56:554/
  still_image_url: http://192.168.86.56:554/snapshot
  name: livingroom
- platform: mjpeg
  name: carport
  still_image_url: http://192.168.86.61/image.jpg
  mjpeg_url: http://192.168.86.61/MJPEG.CGI