- platform: mjpeg
  name: backroom
  mjpeg_url: http://192.168.0.232/media?action=stream&user=admin&pwd=
  still_image_url: http://192.168.0.232/snapshot.cgi?user=admin&pwd=
  verify_ssl: false
- platform: ffmpeg
  input: rtsp://192.168.0.210:554/
  name: camera2
