- platform: sensibo
  api_key: !secret sensibo_api_key
- platform: generic_thermostat
  name: Office
  heater: switch.power2
  target_sensor: sensor.office_temperature_2
  initial_operation_mode: "off"

