- platform: sensibo
  api_key: !secret sensibo_api_key
- platform: generic_thermostat
  name: Office
  heater: switch.koganpow1
  target_sensor: sensor.office_temperature_2
  initial_hvac_mode: "off"
