homeassistant:
  name: Home
  latitude: -33.403710
  longitude: 151.336280
  elevation: 0
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

config:
discovery:
conversation:
logbook:
history:
sun:
system_health:
stream:
person:

logger:
  default: info

http:
  base_url: https://home.adebenham.com:8123
  api_password: !secret http_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
  include_used_components: true

weather:
  - platform: bom
    station: IDN60901.94782

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

googlehome:
  devices:
    - host: 192.168.0.221
      device_types: 1
    - host: 192.168.0.116
      device_types: 1
    - host: 192.168.0.144
      device_types: 1

notify:
  - name: Home assistant
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email
  - name: android
    platform: fcm-android

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret email 
  password: !secret netatmo_password

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state

binary_sensor:
  - platform: huesensor

input_select: !include input_select.yaml
sensor: !include sensors.yaml
custom_updater: !include custom_updater.yaml
camera: !include camera.yaml
google_assistant: !include google.yaml
zone: !include zone.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
scene: !include scene.yaml
group: !include groups.yaml
recorder: !include recorder.yaml
