homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Australia/Sydney
  allowlist_external_dirs:
    - /tmp
  packages: !include_dir_named packages
  customize: !include customize.yaml
  internal_url: https://ha.adebenham.com
  external_url: https://ha.adebenham.com

frontend:
  themes: !include_dir_merge_named themes/

http:
  server_port: 8122
  trusted_proxies:
    - 192.168.86.5
    - 127.0.0.1
    - 172.20.0.0/24
    - 172.18.0.0/24
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://cast.home-assistant.io

logger:
      default: info
    
updater:
  include_used_components: true
    
automation: !include_dir_merge_list automation

# Enable features
discovery:
config:
conversation:
logbook:
history:
sun:
system_health:
stream:
mobile_app:
person:
ffmpeg:
ssdp:
zeroconf:
webhook:
media_source:
wake_on_lan: