homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Australia/Sydney
  packages: !include_dir_named packages
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

discovery:
  ignore:
    - igd
config:
conversation:
logbook:
history:
sun:
system_health:
stream:
person:
ffmpeg:
ssdp:
zeroconf:
webhook:

logger:
  default: info

http:
  base_url: https://ha.adebenham.com
  server_port: 8122
  trusted_proxies:
    - 192.168.86.2
    - 127.0.0.1
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://cast.home-assistant.io

webehome:
  username: !secret webehome_username
  password: !secret webehome_password

entity_controller:
  entry_motion_light:
    sensor: binary_sensor.entry_motion_sensor_occupancy
    entity: light.carport_lights
    delay: 180
    start_time: sunset - 00:30:00
    end_time: sunrise + 00:30:00
    
updater:
  include_used_components: true
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600

upnp:
  port_mapping: false
  sensors: true
  local_ip: 192.168.86.2

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: homeassistant
  max_retries: 3
  default_measurement: state

telegram_bot: !include telegram_bot.yaml
netatmo: !include netatmo.yaml
mqtt: !include mqtt.yaml
hangouts: !include hangouts.yaml
hacs: !include hacs.yaml
geo_location: !include geo_location.yaml
input_select: !include input_select.yaml
sensor: !include sensors.yaml
google_assistant: !include google.yaml
zone: !include zone.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
switch: !include_dir_merge_list switches
life360: !include life.yaml
scene: !include scene.yaml
group: !include groups.yaml
recorder: !include recorder.yaml
media_player: !include media_player.yaml
panel_iframe: !include panel_iframe.yaml
input_boolean: !include input_boolean.yaml
notify: !include notify.yaml
