homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Australia/Sydney
  whitelist_external_dirs:
    - /tmp
  packages: !include_dir_named packages
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

discovery:
config:
conversation:
logbook:
history:
sun:
system_health:
stream:
mobile_app:
person:
ffmpeg:
ssdp:
zeroconf:
webhook:

logger:
  default: info

http:
  base_url: https://ha.adebenham.com
  server_port: 8122
  trusted_proxies:
    - 192.168.86.2
    - 127.0.0.1
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://cast.home-assistant.io

#webehome:
#  username: !secret webehome_username
#  password: !secret webehome_password

entity_controller:
  entry_motion_light:
    sensor:
      - binary_sensor.entry_motion_sensor_occupancy
      - binary_sensor.carport_camera_motion
    entity: light.carport_lights
    delay: 180
    start_time: sunset - 00:30:00
    end_time: sunrise + 00:30:00
    
updater:
  include_used_components: true
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

influxdb:
  host: 192.168.86.2
  port: 8086
  database: homeassistant
  #username: !secret influx_username
  #password: !secret influx_username
  max_retries: 3
  default_measurement: value
  include:
    domains:
      - sensor

telegram_bot: !include telegram_bot.yaml
netatmo: !include netatmo.yaml
mqtt: !include mqtt.yaml
hangouts: !include hangouts.yaml
hacs: !include hacs.yaml
geo_location: !include geo_location.yaml
input_select: !include input_select.yaml
sensor: !include sensors.yaml
google_assistant: !include google.yaml
zone: !include zone.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
switch: !include_dir_merge_list switches
life360: !include life.yaml
scene: !include scene.yaml
group: !include groups.yaml
recorder: !include recorder.yaml
media_player: !include media_player.yaml
panel_iframe: !include panel_iframe.yaml
notify: !include notify.yaml
