homeassistant:
  name: Deane
  packages: !include_dir_named packages
  customize: !include customize.yaml
  external_url: "https://ha.adebenham.com"
  internal_url: "http://192.168.0.10:8122"
  unit_system: metric
  currency: AUD

http:
  server_port: 8122
  trusted_proxies:
    - 192.168.0.10
    - 127.0.0.1
    - 172.0.0.0/8
  use_x_forwarded_for: true
  cors_allowed_origins:
    - https://cast.home-assistant.io

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

logger:
      default: info
    
recorder:
  db_url: !secret db_url
updater:
  include_used_components: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes
