homeassistant:
  name: Home
  latitude: -33.403710
  longitude: 151.336280
  elevation: 0
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

config:
discovery:
conversation:
#logbook:
history:
sun:
system_health:
stream:
person:
ffmpeg:
ssdp:
zeroconf:
webhook:
zigbee2mqtt_networkmap:

logger:
  default: info

http:
  base_url: https://home.adebenham.com:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
  include_used_components: true
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chatid

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret email 
  password: !secret netatmo_password

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state


mqtt:
  broker: 192.168.86.2
  discovery: true
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600

upnp:
  port_mapping: false
  sensors: true
  local_ip: 192.168.86.2

hangouts:
  intents:
    HangoutsHelp:
      sentences:
        - Help
    LivingRoomTemperature:
      sentences:
        - What is the temperature in the living room
  default_conversations:
    - id: hangout_id
  error_suppressed_conversations:
    - id: hangout_id

wemo:
  static:
    - 192.168.86.37

hacs:
  token: !secret github_access_token
  appdaemon: true
  python_script: true
  theme: true

geo_location:
  - platform: nsw_rural_fire_service_feed
    categories:
      - 'Emergency Warning'
      - 'Watch and Act'
      - 'Advice'

input_select: !include input_select.yaml
sensor: !include sensors.yaml
camera: !include camera.yaml
google_assistant: !include google.yaml
zone: !include zone.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
switch: !include_dir_merge_list switches
life360: !include life.yaml
scene: !include scene.yaml
group: !include groups.yaml
recorder: !include recorder.yaml
media_player: !include media_player.yaml
shell_command: !include shell_command.yaml
light: !include light.yaml
panel_iframe: !include panel_iframe.yaml
input_boolean: !include input_boolean.yaml
notify: !include notify.yaml
climate: !include climate.yaml
