homeassistant:
  name: Home
  latitude: -33.403710
  longitude: 151.336280
  elevation: 0
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

config:
discovery:
conversation:
#logbook:
history:
sun:
system_health:
stream:
person:
ffmpeg:
ssdp:
zeroconf:
webhook:
zigbee2mqtt_networkmap:

logger:
  default: info

http:
  base_url: https://home.adebenham.com:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

updater:
  include_used_components: true
    
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

notify:
  - name: Home assistant
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email
  - name: Hangout Notify
    platform: hangouts
    default_conversations:
      - id: hangout_id

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret email 
  password: !secret netatmo_password

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_username
  password: !secret influx_password
  max_retries: 3
  default_measurement: state


mqtt:
  broker: 192.168.86.2
  discovery: true
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600

upnp:
  port_mapping: false
  sensors: true
  local_ip: 192.168.86.2

hangouts:
  intents:
    HangoutsHelp:
      sentences:
        - Help
    LivingRoomTemperature:
      sentences:
        - What is the temperature in the living room
  default_conversations:
    - id: hangout_id
  error_suppressed_conversations:
    - id: hangout_id

input_select: !include input_select.yaml
sensor: !include sensors.yaml
custom_updater: !include custom_updater.yaml
camera: !include camera.yaml
google_assistant: !include google.yaml
zone: !include zone.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml
switch: !include_dir_merge_list switches
device_tracker: !include device_tracker.yaml
scene: !include scene.yaml
group: !include groups.yaml
recorder: !include recorder.yaml
media_player: !include media_player.yaml
shell_command: !include shell_command.yaml
light: !include light.yaml
panel_iframe: !include panel_iframe.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
