- platform: template
  fans:
    kitchen_fan:
      friendly_name: "Kitchen Fan"
      value_template: "{{ states('switch.kitchen_relay_3.state') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.kitchen_relay_3
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.kitchen_relay_3