- platform: group
  name: Backroom Light Group
  entities:
    - light.backroom_middle
    - light.backroom_left
    - light.backroom_right
- platform: group
  name: Kitchen Light Group
  entities:
    - light.kitchen_front
    - light.kitchen_back
    - light.kitchen_counter_light
- platform: group
  name: Bedroom Light Group
  entities:
    - light.bedrooma
    - light.bedroomb
- platform: group
  name: Livingroom Light Group
  entities:
    - light.livingroom_side
    - light.livingroom_a
    - light.livingroom_b
- platform: group
  name: Hall Light Group
  entities:
    - light.hall_color
    - light.hall_white
- platform: group
  name: Entry Light Group
  entities:
    - light.bulb_color_3
    - light.bulb_white_3
- platform: switch
  name: Toilet
  entity_id:
    - switch.toilet_light
