- platform: group
  name: Backroom Light Group
  icon: mdi:castle
  entities:
    - light.family_room_middle
    - light.family_room_right
    - light.family_room_left
- platform: group
  name: Living Room Light Group
  icon: mdi:sofa
  entities:
    - light.living_room_1
    - light.living_room_2
    - light.livingroom_side
- platform: group
  name: Office Light Group
  icon: mdi:desktop-classic
  entities:
    - light.office
- platform: group
  name: Bedroom Light Group
  icon: mdi:bed-empty
  entities:
    - light.bedroom_light_1
    - light.bedroom_light_2
- platform: group
  name: Craft Room Light Group
  icon: mdi:content-cut
  entities:
    - light.craft_room
- platform: group
  name: Kitchen Light Group
  icon: mdi:fridge
  entities:
    - light.kitchen_light_back
    - light.kitchen_light_front
    - light.kitchen_counter
- platform: group
  name: Xander Bedroom Light Group
  icon: mdi:bed-empty
  entities:
    - light.xander_bedroom_light
- platform: group
  name: Lucas Bedroom Light Group
  icon: mdi:bed-empty
  entities:
    - light.lucas_bedroom_light
- platform: group
  name: Hall Light Group
  entities:
    - light.hall_white
    - light.hall_colour
- platform: group
  name: Entry Light Group
  icon: mdi:door
  entities:
    - light.bulb_white_3
    - light.bulb_colour_3
- platform: group
  name: Front Light Group
  icon: mdi:car
  entities:
    - light.sensor_light
