- platform: universal
  name: "Livingroom TV"
  children:
    - media_player.living_room_tv
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.lg_amp
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.lg_amp
    volume_up:
      service: switch.turn_on
      data:
        entity_id: switch.lg_amp_volup
    volume_down:
      service: switch.turn_on
      data:
        entity_id: switch.lg_amp_voldown
    select_source:
      service:  input_select.select_option
      data:
        entity_id: input_select.livingroom_amp_input
  attributes:
    source: input_select.livingroom_amp_input
    source_list: input_select.livingroom_amp_input
    state: switch.lg_amp
