int:
  title: 'Internal'
  url: 'https://home.adebenham.com/int/mux/'
  icon: mdi:cloud-download
  require_admin: true
grafana:
  title: 'Grafana'
  url: 'https://home.adebenham.com/int/grafana/'
  icon: mdi:chart-timeline-variant
  require_admin: true
vscode:
  title: 'VSCode'
  url: 'https://home.adebenham.com/int/vscode/'
  icon: mdi:code-tags
  require_admin: true
esphome:
  title: 'ESPHome'
  url: 'https://home.adebenham.com/int/esphome/'
  icon: mdi:cog
  require_admin: true
zm:
  title: 'ZoneMinder'
  url: 'https://home.adebenham.com/zm/?view=montage'
  icon: mdi:video
  require_admin: true
nodered:
  title: 'NodeRed'
  url: 'https://home.adebenham.com/int/nodered'
  icon: mdi:sitemap
  require_admin: true
