- platform: bom
  station: IDN60901.94782
  name: Gosford
  monitored_conditions:
    - apparent_t
    - delta_t
    - gust_kmh
    - gust_kt
    - air_temp
    - dewpt
    - rain_trace
    - rel_hum
    - weather
    - wind_dir
    - wind_spd_kmh
    - wind_spd_kt
- platform: bom_forecast
  product_id: IDN11052
  name: Gosford
  forecast_days: 6
  rest_of_today: true
  friendly: false
  friendly_state_format: '{max}, {summary}'
  monitored_conditions:
    - 'max'
    - 'min'
    - 'chance_of_rain'
    - 'possible_rainfall'
    - 'summary'
    - 'detailed_summary'
    - 'icon'
- platform: efergy
  app_token: !secret efergy_app_token
  utc_offset: UTC_OFFSET
  monitored_variables:
    - type: instant_readings
- platform: template
  sensors:
    tvpower:
      value_template: '{{ states.switch.entertainment_unit.attributes["current_power_w"] }}'
      unit_of_measurement: 'W'
      friendly_name: "TV Power Usage"
    sensibo_temperature:
      value_template: '{{ states.climate.living_room.attributes["current_temperature"] }}'
      unit_of_measurement: '°C'
      friendly_name: "Livingroom Temperature"
    sensibo_humidity:
      value_template: '{{ states.climate.living_room.attributes["current_humidity"] }}'
      unit_of_measurement: '%'
      friendly_name: "Livingroom Humidity"
    melphone_battery:
      value_template: '{{ states.device_tracker.life360_mel.attributes["battery"] }}'
      unit_of_measurement: '%'
      friendly_name: "Mels Battery"
    chrisphone_battery:
      value_template: '{{ states.device_tracker.life360_chris.attributes["battery"] }}'
      unit_of_measurement: '%'
      friendly_name: "Chris' Battery"
    bom_current_text:
      value_template: >
          {% set val = states('sensor.bom_gosford_summary_0').split('.')[0] %} 
          {{ val | title }}
    bom_forecast_0:
      entity_id:
        - sensor.bom_today_max
        - sensor.bom_today_min
        - sensor.bom_gosford_chance_of_rain_0
        - sensor.bom_gosford_icon_0
      friendly_name: "Today"
      value_template: >
        {{states('sensor.bom_today_max')|round(0)}}°/{{states('sensor.bom_today_min')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_0')|round(0)}}%
      entity_picture_template: >-
        {%- if now().strftime('%H:%M') > '18:00' and (states('sensor.bom_gosford_icon_0') == 'fog' or states('sensor.bom_gosford_icon_0') == 'haze' or states('sensor.bom_gosford_icon_0') == ' light-showers' or states('sensor.bom_gosford_icon_0') == 'partly-cloudy' or states('sensor.bom_gosford_icon_0') == 'showers') -%}
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_0') ~ '-night.png' }}
        {%- else -%}
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_0') ~ '.png' }}
        {%- endif -%}
    bom_forecast_1:
      entity_id:
        - sensor.bom_gosford_max_temp_c_1
        - sensor.bom_gosford_min_temp_c_1
        - sensor.bom_gosford_chance_of_rain_1
        - sensor.bom_gosford_icon_1
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
        {{ date | timestamp_custom('Tomorrow (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_gosford_max_temp_c_1')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_1')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_1')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_1') ~ '.png' }}
    bom_forecast_2:
      entity_id:
        - sensor.bom_gosford_max_temp_c_2
        - sensor.bom_gosford_min_temp_c_2
        - sensor.bom_gosford_chance_of_rain_2
        - sensor.bom_gosford_icon_2
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_gosford_max_temp_c_2')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_2')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_2')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_2') ~ '.png' }}
    bom_forecast_3:
      entity_id:
        - sensor.bom_gosford_max_temp_c_3
        - sensor.bom_gosford_min_temp_c_3
        - sensor.bom_gosford_chance_of_rain_3
        - sensor.bom_gosford_icon_3
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_gosford_max_temp_c_3')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_3')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_3')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_3') ~ '.png' }}
    bom_forecast_4:
      entity_id:
        - sensor.bom_gosford_max_temp_c_4
        - sensor.bom_gosford_min_temp_c_4
        - sensor.bom_gosford_chance_of_rain_4
        - sensor.bom_gosford_icon_4
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_gosford_max_temp_c_4')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_4')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_4')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_4') ~ '.png' }}
    bom_forecast_5:
      entity_id:
        - sensor.bom_gosford_max_temp_c_5
        - sensor.bom_gosford_min_temp_c_5
        - sensor.bom_gosford_chance_of_rain_5
        - sensor.bom_gosford_icon_5
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_gosford_max_temp_c_5')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_5')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_5')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_5') ~ '.png' }}
    bom_forecast_6:
      entity_id:
        - sensor.bom_gosford_max_temp_c_6
        - sensor.bom_gosford_min_temp_c_6
        - sensor.bom_gosford_chance_of_rain_6
        - sensor.bom_gosford_icon_6
      friendly_name_template: >
        {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
        {{ date | timestamp_custom('%A (%-d/%-m)') }}
      value_template: >
        {{states('sensor.bom_gosford_max_temp_c_6')|round(0)}}°/{{states('sensor.bom_gosford_min_temp_c_6')|round(0)}}°/{{states('sensor.bom_gosford_chance_of_rain_6')|round(0)}}%
      entity_picture_template: >-
        {{ '/local/icons/bom_icons/' ~ states('sensor.bom_gosford_icon_6') ~ '.png' }}
    bom_today_max:
      entity_id:
        - sensor.bom_gosford_max_temp_c_0
        - sensor.today_temp_bom_mean
      value_template: >
        {%- if states('sensor.bom_gosford_max_temp_c_0') == 'n/a' -%} 
          {{ state_attr('sensor.today_temp_bom_mean', 'max_value') }}
        {% else %}
          {{ states('sensor.bom_gosford_max_temp_c_0') }}
        {% endif %}
    bom_today_min:
      entity_id:
        - sensor.bom_gosford_min_temp_c_0
        - sensor.today_temp_bom_mean
      value_template: >
        {%- if states('sensor.bom_gosford_min_temp_c_0') == 'n/a' -%} 
          {{ state_attr('sensor.today_temp_bom_mean', 'min_value') }}
        {% else %}
          {{ states('sensor.bom_gosford_min_temp_c_0') }}
        {% endif %}
- platform: statistics
  name: today_temp_bom
  sampling_size: 150
  entity_id: sensor.bom_gosford_air_temp_c
  max_age:
    hours: 24

- platform: filter
  name: "House Power"
  entity_id: sensor.energy_usage
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: range
      upper_bound: 1200
- platform: google_wifi
  host: 192.168.86.1
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    - type: disk_free
      arg: /
