- platform: bom
  station: IDN60901.94782
  name: Gosford
  monitored_conditions:
    - air_temp
    - weather
    - wind_dir
    - wind_spd_kmh
- platform: efergy
  app_token: !secret efergy_app_token
  utc_offset: UTC_OFFSET
  monitored_variables:
    - type: instant_readings
- platform: template
  sensors:
    tvpower:
      value_template: '{{ states.switch.entertainment_unit.attributes["current_power_w"] }}'
      unit_of_measurement: 'W'
      friendly_name: "TV Power Usage"
    sensibo_temperature:
      value_template: '{{ states.climate.living_room.attributes["current_temperature"] }}'
      unit_of_measurement: '°C'
      friendly_name: "Livingroom Temperature"
    sensibo_humidity:
      value_template: '{{ states.climate.living_room.attributes["current_humidity"] }}'
      unit_of_measurement: '%'
      friendly_name: "Livingroom Humidity"
    melphone_battery:
      value_template: '{{ states.device_tracker.life360_mel.attributes["battery"] }}'
      unit_of_measurement: '%'
      friendly_name: "Mels Battery"
    chrisphone_battery:
      value_template: '{{ states.device_tracker.life360_chris.attributes["battery"] }}'
      unit_of_measurement: '%'
      friendly_name: "Chris' Battery"
      
- platform: filter
  name: "House Power"
  entity_id: sensor.energy_usage
  filters:
    - filter: outlier
      window_size: 4
      radius: 2.0
    - filter: range
      upper_bound: 1200
- platform: broadlink
  host: 192.168.86.38
  mac: 'C8:F7:42:16:AD:21'
  monitored_conditions:
     - 'temperature'
- platform: google_wifi
  host: 192.168.86.1
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
