- platform: command_line
  switches:
    backroom_up:
      command_on: '/config/ptz_script.sh 1'
      command_off: '/config/ptz_script.sh 1'
    backroom_down:
      command_on: '/config/ptz_script.sh 2'
      command_off: '/config/ptz_script.sh 2'
    backroom_right:
      command_on: '/config/ptz_script.sh 3'
      command_off: '/config/ptz_script.sh 3'
    backroom_left:
      command_on: '/config/ptz_script.sh 4'
      command_off: '/config/ptz_script.sh 4'
- platform: template
  switches:
    livingroom_lights:
      icon_template: mdi:sofa
      friendly_name: "Livingroom"
      value_template: "{{ not is_state('input_select.livingroom_preset', 'TurnOff') }}"
      turn_on:
        service: input_select.select_option
        data:
          entity_id: input_select.livingroom_preset
          option: "Normal"
      turn_off:
        service: input_select.select_option
        data:
          entity_id: input_select.livingroom_preset
          option: "TurnOff"
    kitchen_lights:
      icon_template: mdi:fridge
      friendly_name: "Kitchen"
      value_template: "{{ states('group.kitchen_lights') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
            entity_id: group.kitchen_lights
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.kitchen_lights
    backroom_lights:
      icon_template: mdi:castle
      friendly_name: "Backroom"
      value_template: "{{ states('group.backroom_lights') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
            entity_id: group.backroom_lights
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.backroom_lights
    craftroom_lights:
      icon_template: mdi:content-cut
      friendly_name: "Craft"
      value_template: "{{ states('group.craftroom_lights') }}"
      turn_on:
        service: homeassistant.turn_on
        data:
            entity_id: group.craftroom_lights
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.craftroom_lights
    office_lights:
      value_template: "{{ states('group.office_lights') }}"
      icon_template: mdi:desktop-classic
      friendly_name: "Office"
      turn_on:
        service: homeassistant.turn_on
        data:
            entity_id: group.office_lights
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.office_lights
    bedroom_lights:
      value_template: "{{ states('group.bedroom_lights') }}"
      icon_template: mdi:bed-empty
      friendly_name: "Bedroom"
      turn_on:
        service: homeassistant.turn_on
        data:
            entity_id: group.bedroom_lights
      turn_off:
        service: homeassistant.turn_off
        data:
            entity_id: group.bedroom_lights
