cch:
  swipe: true
  voice: hide
resources:
- type: module
  url: /community_plugin/mini-graph-card/mini-graph-card.js
- type: module
  url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
- type: module
  url: /community_plugin/light-entity-row/light-entity-row.js
- type: module
  url: /community_plugin/monster-card/monster-card.js
- type: module
  url: /community_plugin/simple-thermostat/simple-thermostat.js
- type: module
  url: /community_plugin/simple-thermostat/simple-thermostat.js
- type: module
  url: /community_plugin/button-card/button-card.js
- type: module
  url: /community_plugin/compact-custom-header/compact-custom-header.js
- type: module
  url: /community_plugin/mini-media-player/mini-media-player.js
- type: module
  url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
- type: module
  url: /community_plugin/bom-weather-card/bom-weather-card.js
title: Home
views:
- badges:
  - device_tracker.life360_mel
  - device_tracker.life360_chris
  - sensor.sensibo_temperature
  - sensor.entry_motion_temperature
  - sensor.bedroom_temperature
  cards:
  - entities:
    - entity: binary_sensor.hall_smoke
      name: Smoke Detector
    - entity: binary_sensor.frontdoor_contact
      name: Front Door
    - entity: binary_sensor.backdoor_sensor_contact
      name: Back Door
    - entity: binary_sensor.ac_active_sensor_contact
      name: Air Conditioner
    - entity: binary_sensor.livingroom_window_sensor_contact
    - entity: binary_sensor.bedroom_window_contact
      name: Bedroom Window
    show_empty: false
    state_filter:
    - 'on'
    type: entity-filter
  - cards:
    - cards:
      - color: rgb(5, 147, 255)
        color-type: card
        entity: switch.bedroom_light_group
        hold_action:
          action: more-info
          entity: light.bedroom_light_group
        icon: mdi:bed-empty
        name: Main
        type: custom:button-card
      - color: rgb(5, 147, 255)
        color-type: card
        entity: switch.lucas_bedroom_light
        hold_action:
          action: more-info
          entity: light.lucas_bedroom_light
        icon: mdi:bed-empty
        name: Lucas
        type: custom:button-card
      - color: rgb(5, 147, 255)
        color-type: card
        entity: switch.xander_bedroom_light
        hold_action:
          action: more-info
          entity: light.xander_bedroom_light
        icon: mdi:bed-empty
        name: Xander
        type: custom:button-card
      type: horizontal-stack
    - cards:
      - color: rgb(5, 147, 255)
        entity: switch.livingroom_light_group
        hold_action:
          action: more-info
          entity: light.livingroom_light_group
        icon: mdi:sofa
        name: Livingroom
        type: custom:button-card
      - color: rgb(5, 147, 255)
        entity: switch.kitchen_light_group
        hold_action:
          action: more-info
          entity: light.kitchen_light_group
        icon: mdi:fridge
        name: Kitchen
        type: custom:button-card
      - color: rgb(5, 147, 255)
        entity: switch.backroom_light_group
        hold_action:
          action: more-info
          entity: light.backroom_light_group
        icon: mdi:castle
        name: Backroom
        type: custom:button-card
      - color: rgb(5, 147, 255)
        entity: switch.craftroom_light
        hold_action:
          action: more-info
          entity: light.craftroom_light
        icon: mdi:content-cut
        name: Craft
        type: custom:button-card
      type: horizontal-stack
    - cards:
      - color: rgb(5, 147, 255)
        entity: switch.office_light
        hold_action:
          action: more-info
          entity: light.office_light
        name: Office
        type: custom:button-card
      - color: rgb(5, 147, 255)
        color-type: card
        entity: switch.entry_lights
        hold_action:
          action: more-info
          entity: group.entry_lights
        name: Entry
        type: custom:button-card
      - color: rgb(5, 147, 255)
        color-type: card
        entity: switch.hall_lights
        hold_action:
          action: more-info
          entity: group.hall_lights
        name: Hall
        type: custom:button-card
      - color: rgb(5, 147, 255)
        color-type: card
        entity: switch.front_lights
        hold_action:
          action: more-info
          entity: light.sensor_light
        name: Front door
        type: custom:button-card
      type: horizontal-stack
    - color: rgb(44, 109, 214)
      color_type: label-card
      name: Scenes
      type: custom:button-card
    - cards:
      - entity: input_select.livingroom_preset
        icon: mdi:lightbulb
        name: Normal
        state:
        - color: rgb(5, 147, 255)
          value: Normal
        - color: var(--paper-item-icon-color)
          operator: default
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.livingroom_preset
            option: Normal
        type: custom:button-card
      - entity: input_select.livingroom_preset
        icon: mdi:movie
        name: Movie
        state:
        - color: rgb(5, 147, 255)
          value: Movie
        - color: var(--paper-item-icon-color)
          operator: default
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.livingroom_preset
            option: Movie
        type: custom:button-card
      - entity: input_select.livingroom_preset
        icon: mdi:weather-night
        name: Night
        state:
        - color: rgb(5, 147, 255)
          value: Night
        - color: var(--paper-item-icon-color)
          operator: default
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.livingroom_preset
            option: Night
        type: custom:button-card
      - entity: input_select.livingroom_preset
        icon: mdi:do-not-disturb
        name: 'Off'
        state:
        - color: rgb(5, 147, 255)
          value: TurnOff
        - color: var(--paper-item-icon-color)
          operator: default
        tap_action:
          action: call-service
          service: input_select.select_option
          service_data:
            entity_id: input_select.livingroom_preset
            option: TurnOff
        type: custom:button-card
      type: horizontal-stack
    type: vertical-stack
  - entity: climate.living_room
    modes:
      dry: false
      fan_only: false
      heat_cool: false
    sensors:
    - entity: sensor.netatmo_outdoor_temperature
    step_size: 1
    type: custom:simple-thermostat
  icon: mdi:home
  panel: false
  path: default_view
  title: Home
- badges: []
  cards:
  - apparent_right_margin: 1em
    apparent_right_pos: 1em
    apparent_top_margin: 45px
    current_data_top_margin: 7em
    current_text_font_size: 1.5em
    current_text_left_pos: 5em
    current_text_top_margin: 39px
    entity_apparent_temp: sensor.bom_gosford_feels_like_c
    entity_current_conditions: sensor.bom_gosford_icon_0
    entity_current_text: sensor.bom_current_text
    entity_daily_summary: sensor.bom_gosford_detailed_summary_0
    entity_daytime_high: sensor.bom_today_max
    entity_daytime_low: sensor.bom_today_min
    entity_forecast_high_temp_1: sensor.bom_gosford_max_temp_c_1
    entity_forecast_high_temp_2: sensor.bom_gosford_max_temp_c_2
    entity_forecast_high_temp_3: sensor.bom_gosford_max_temp_c_3
    entity_forecast_high_temp_4: sensor.bom_gosford_max_temp_c_4
    entity_forecast_high_temp_5: sensor.bom_gosford_max_temp_c_5
    entity_forecast_icon_1: sensor.bom_gosford_icon_1
    entity_forecast_icon_2: sensor.bom_gosford_icon_2
    entity_forecast_icon_3: sensor.bom_gosford_icon_3
    entity_forecast_icon_4: sensor.bom_gosford_icon_4
    entity_forecast_icon_5: sensor.bom_gosford_icon_5
    entity_forecast_low_temp_1: sensor.bom_gosford_min_temp_c_1
    entity_forecast_low_temp_2: sensor.bom_gosford_min_temp_c_2
    entity_forecast_low_temp_3: sensor.bom_gosford_min_temp_c_3
    entity_forecast_low_temp_4: sensor.bom_gosford_min_temp_c_4
    entity_forecast_low_temp_5: sensor.bom_gosford_min_temp_c_5
    entity_humidity: sensor.bom_gosford_relative_humidity
    entity_pop: sensor.bom_gosford_chance_of_rain_0
    entity_pop_1: sensor.bom_gosford_chance_of_rain_1
    entity_pop_2: sensor.bom_gosford_chance_of_rain_2
    entity_pop_3: sensor.bom_gosford_chance_of_rain_3
    entity_pop_4: sensor.bom_gosford_chance_of_rain_4
    entity_pop_5: sensor.bom_gosford_chance_of_rain_5
    entity_pop_intensity: sensor.bom_gosford_rain_today
    entity_pos_1: sensor.bom_gosford_possible_rainfall_1
    entity_pos_2: sensor.bom_gosford_possible_rainfall_2
    entity_pos_3: sensor.bom_gosford_possible_rainfall_3
    entity_pos_4: sensor.bom_gosford_possible_rainfall_4
    entity_pos_5: sensor.bom_gosford_possible_rainfall_5
    entity_possible_today: sensor.bom_gosford_possible_rainfall_0
    entity_summary_1: sensor.bom_gosford_summary_1
    entity_summary_2: sensor.bom_gosford_summary_2
    entity_summary_3: sensor.bom_gosford_summary_3
    entity_summary_4: sensor.bom_gosford_summary_4
    entity_summary_5: sensor.bom_gosford_summary_5
    entity_sun: sun.sun
    entity_temperature: sensor.entry_motion_temperature
    entity_wind_bearing: sensor.bom_gosford_wind_direction
    entity_wind_speed: sensor.bom_gosford_wind_speed_kmh
    large_icon_left_position: 0em
    large_icon_top_margin: -3.5em
    locale: en
    old_daily_format: false
    refresh_interval: 60
    separator_top_margin: 6em
    show_beaufort: false
    show_separator: false
    slot_l1: daytime_high
    slot_l2: daytime_low
    slot_l3: wind
    slot_l4: sun_next
    slot_r1: pop
    slot_r2: humidity
    slot_r3: possible_today
    slot_r4: sun_following
    static_icons: false
    sunset: true
    temp_font_size: 4em
    temp_font_weight: 300
    temp_right_pos: 0.85em
    temp_top_margin: -0.3em
    temp_uom_right_margin: 7px
    temp_uom_top_margin: -9px
    time_format: 12
    title: BOM Weather
    tooltip_bg_color: rgb( 75,155,239)
    tooltip_border_color: rgb(255,161,0)
    tooltip_border_width: 1
    tooltip_caret_size: 5
    tooltip_fg_color: '#fff'
    tooltip_left_offset: -12
    tooltip_width: 110
    tooltips: true
    type: custom:bom-weather-card
  - entity: camera.bom_radar_loop_sydney
    type: picture-entity
  - entities:
    - entity: sensor.entry_motion_temperature
    - entity: sensor.netatmo_indoor_temperature
      name: Livingroom Temperature
    - entity: sensor.bedroom_temperature
      name: Main Bedroom Temperature
    - entity: sensor.lucas_bedroom_sensor_temperature
    - entity: sensor.xander_bedroom_sensor_temperature
    - entity: sensor.netatmo_outdoor_temperature
      name: Backyard Temperature
    - entity: sensor.office_temperature_2
    show_header_toggle: false
    title: Temperatures
    type: entities
  - entities:
    - entity: sensor.bom_gosford_air_temp_c
      name: BOM Air Temperature
    - entity: sensor.netatmo_outdoor_temperature
      name: Backyard Temperature
    - entity: sensor.entry_motion_temperature
      name: Carport Temperature
    - entity: sensor.bedroom_temperature
    - entity: sensor.entry_motion_temperature
    - entity: sensor.netatmo_indoor_temperature
      name: Livingroom Temperature
    - entity: sensor.bedroom_temperature
      name: Main Bedroom Temperature
    - entity: sensor.lucas_bedroom_sensor_temperature
    - entity: sensor.xander_bedroom_sensor_temperature
    - entity: sensor.netatmo_outdoor_temperature
      name: Backyard Temperature
    - entity: sensor.office_temperature_2
    hours_to_show: 48
    type: history-graph
  - entities:
    - entity: sensor.netatmo_indoor_humidity
      name: Indoor Humidity
    - entity: sensor.sensibo_humidity
      name: Indoor Humidity 2
    - entity: sensor.netatmo_outdoor_humidity
      name: Outdoor Humidity
    - entity: sensor.lucas_bedroom_sensor_humidity
    - entity: sensor.xander_bedroom_sensor_humidity
    hours_to_show: 48
    type: history-graph
  - entities:
    - entity: sensor.netatmo_indoor_pressure
      name: Living Room Pressure
    - entity: sensor.office_pressure
    - entity: sensor.bedroom_pressure
    hours_to_show: 72
    type: history-graph
  icon: mdi:cloud
  panel: false
  title: Charts
- badges: []
  cards:
  - entities:
    - entity: light.bedroom_light_group
      name: Main Bedroom
      type: custom:slider-entity-row
    - entity: light.backroom_light_group
      name: Backroom
      type: custom:slider-entity-row
    - entity: light.craftroom_light
      name: Craftroom
      type: custom:slider-entity-row
    - entity: light.kitchen_light_group
      name: Kitchen
      type: custom:slider-entity-row
    - entity: light.livingroom_light_group
      name: Livingroom
      type: custom:slider-entity-row
    - entity: light.office_light
      type: custom:slider-entity-row
    - entity: light.lucas_bedroom_light
      type: custom:slider-entity-row
    - entity: light.xander_bedroom_light
      type: custom:slider-entity-row
    - entity: light.bulb_white_3
      type: custom:slider-entity-row
    - entity: light.hall_white
      type: custom:slider-entity-row
    - entity: light.sensor_light
    show_header_toggle: false
    title: Rooms
    type: entities
  - entities:
    - buttons:
      - name: Random Colours
        service_data:
          effect: Slow Random Effect
      - name: Twinkle
        service_data:
          effect: Random Twinkle
      - name: Rainbow
        service_data:
          effect: Rainbow
      entity: light.tv_backlight_2
      hideBrightness: true
      hideColorTemp: true
      showColorSliders: false
      type: custom:light-entity-row
    - buttons:
      - name: Random Colours
        service_data:
          effect: Slow Random Effect
      - name: Twinkle
        service_data:
          effect: Random Twinkle
      - name: Rainbow
        service_data:
          effect: Rainbow
      entity: light.family_room_strip
      hideBrightness: true
      hideColorTemp: true
      type: custom:light-entity-row
    show_header_toggle: false
    title: Light Strips
    type: entities
  - entities:
    - entity: switch.office_speaker
    show_header_toggle: false
    title: Switches
    type: entities
  icon: mdi:lightbulb
  panel: false
  title: Lights
- badges: []
  cards:
  - entity: camera.carport
    type: picture-entity
  - camera_image: camera.livingroom
    entity: camera.livingroom
    name: Livingroom
    type: picture-entity
  - camera_image: camera.backroom
    camera_view: live
    entities:
    - entity: switch.backroom_ptz_home
      icon: mdi:do-not-disturb
    - entity: switch.backroom_ptz_away
      icon: mdi:home
    - entity: switch.backroom_ptz_up
      icon: mdi:arrow-up-thick
    - entity: switch.backroom_ptz_down
      icon: mdi:arrow-down-thick
    - entity: switch.backroom_ptz_left
      icon: mdi:arrow-left-thick
    - entity: switch.backroom_ptz_right
      icon: mdi:arrow-right-thick
    type: picture-glance
  - entity: camera.minicam
    name: Backyard
    type: picture-entity
  icon: mdi:camera
  title: Cameras
- badges: []
  cards:
  - entity: media_player.livingroom_tv
    hide:
      mute: true
    source: full
    toggle_power: false
    type: custom:mini-media-player
    volume_stateless: true
  - entities:
    - entity: switch.lg_amp
    - entity: switch.livingroomtv
    - entity: input_select.livingroom_amp_input
    show_header_toggle: false
    type: entities
  - entities:
    - entity: media_player.whole_house
      group: true
      hide:
        power: true
        volume: true
      info: short
      source: icon
      type: custom:mini-media-player
    - entity: media_player.family_room_speaker
      group: true
      hide:
        controls: true
      type: custom:mini-media-player
    - entity: media_player.living_room_display
      group: true
      hide:
        controls: true
      type: custom:mini-media-player
    - entity: media_player.googlehome2690
      group: true
      hide:
        controls: true
      type: custom:mini-media-player
    - entity: media_player.living_room_mini
      group: true
      hide:
        controls: true
      type: custom:mini-media-player
    type: entities
  - entity: media_player.living_room_display
    type: custom:mini-media-player
  - entity: media_player.bedroom_tv
    type: custom:mini-media-player
  icon: mdi:movie
  title: Media
- badges: []
  cards:
  - default_zoom: 13
    entities:
    - entity: device_tracker.life360_mel
    - entity: device_tracker.life360_chris
    geo_location_sources:
    - all
    type: map
  icon: mdi:map
  panel: true
  title: Map
- badges: []
  cards:
  - card:
      title: Notices
      type: glance
    filter:
      include:
      - attributes:
          linkquality: < 20
        entity_id: sensor.*linkquality
      - attributes:
          battery: < 50
        domain:
        - ()
    type: custom:monster-card
  - entities:
    - entity: binary_sensor.hall_smoke
      name: Smoke Detector
    - entity: binary_sensor.frontdoor_contact
      name: Front Door
    - entity: binary_sensor.backdoor_sensor_contact
      name: Back Door
    - entity: binary_sensor.ac_active_sensor_contact
      name: AC Power sensor
    - entity: binary_sensor.livingroom_window_sensor_contact
    - entity: binary_sensor.pantry_contact
    - entity: binary_sensor.bedroom_window_contact
    - entity: binary_sensor.back_screen_door_contact
    show_icon: true
    type: glance
  - entities:
    - entity: input_boolean.zigbee_permit_join
    - entity: timer.zigbee_permit_join
    - entity: sensor.bridge_state
    show_header_toggle: false
    title: Zigbee
    type: entities
  - card:
      title: Battery level
      type: history-graph
    filter:
      include:
      - entity_id: sensor.*battery
    hours: 48
    type: custom:monster-card
  - entity: climate.office
    type: thermostat
  - entities:
    - sensor.house_power
    - sensor.tvpower
    hours_to_show: 24
    type: history-graph
  - entities:
    - entity: sensor.netatmo_indoor_noise
      name: Noise level
    type: history-graph
  - entities:
    - sensor.load_1m
    - sensor.processor_use
    - sensor.load_5m
    - sensor.load_15m
    - sensor.memory_use_percent
    - sensor.last_boot
    - sensor.disk_free
    title: System Stats
    type: history-graph
  icon: mdi:settings
  title: ''
