esphome:
  name: ${device}
  platform: ESP8266
  board: ${board}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:


# Enable logging
logger:

# Enable Home Assistant API
#api:

mqtt:
  broker: 192.168.86.5
  username: !secret mqtt_username
  password: !secret mqtt_password
  #discovery: false

ota:
