wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} Fallback Hotspot"
    password: !secret wifi_password

captive_portal:

web_server:
  port: 80
  css_url: http://dock/int/esphome/webserver-v1.min.css
  js_url: http://dock/int/esphome/webserver-v1.min.js

# Enable logging
logger:

# Enable ESPHome API
#api:

mqtt:
  broker: 192.168.86.5
  username: !secret mqtt_username
  password: !secret mqtt_password
  #discovery: false

ota:
