light:
  - platform: template
    lights:
      bathroom_lights:
        friendly_name: Bathroom Lights
        turn_on:
          service: script.noop
        turn_off:
          service: script.noop

automation:
  - id: '1620862005725'
    alias: Bathroom - Moon On at Sunset
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.night_mode
        to: "on"
    condition: []
    action:
    - service: light.turn_on
      target:
        entity_id: light.bathroom_moon
      data:
        brightness_pct: 25
        rgbww_color: [0, 0, 0, 0, 255]
    mode: single
  - id: '1620862057642'
    alias: Bathroom - Moon Off at sunrise
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.night_mode
        to: "off"
    condition: []
    action:
    - service: light.turn_off
      target:
        entity_id: light.bathroom_moon
    mode: single
