light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedroomdimmer

template:
  - sensor:
    - name: "Bedroom Wattage"
      unit_of_measurement: W
      state_class: measurement
      device_class: energy
      state: "{{ states('sensor.bedroomdimmer_power')|float(0)
               + states('sensor.bedroombedplug_energy_power')|float(0)
               + states('sensor.bedroomplug_energy_power')|float(0)}}"

automation:
  - id: '1610172763965'
    alias: Bedroom - Kid indicator on
    trigger:
    - platform: state
      entity_id: light.lucas_lights
    - platform: state
      entity_id: light.xander_lights
    - platform: state
      entity_id: binary_sensor.chrisphone_is_charging
    condition: 
      and:
        - condition: state
          entity_id: binary_sensor.chrisphone_is_charging
          state: 'true'
        - or:
          - condition: state
            entity_id: light.lucas_lights
            state: 'on'
          - condition: state
            entity_id: light.xander_lights
            state: 'on'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_led
        brightness_pct: 40
        color_name: '{% if is_state(''light.lucas_lights'', ''on'') and is_state(''light.xander_lights'',
          ''on'') %} red {% elif is_state(''light.lucas_lights'', ''off'') and is_state(''light.xander_lights'',
          ''on'') %} green {% elif is_state(''light.lucas_lights'', ''on'') and is_state(''light.xander_lights'',
          ''off'') %} blue {% else %} black {% endif %}'
  - id: '1610172763966'
    alias: Bedroom - Kid indicator off
    trigger:
    - platform: state
      entity_id: light.lucas_lights
    - platform: state
      entity_id: light.xander_lights
    - platform: state
      entity_id: binary_sensor.chrisphone_is_charging
    condition: 
      or:
        - condition: state
          entity_id: binary_sensor.chrisphone_is_charging
          state: 'false'
        - and:
          - condition: state
            entity_id: light.lucas_lights
            state: 'off'
          - condition: state
            entity_id: light.xander_lights
            state: 'off'
    action:
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom_led
  - id: '1610190580265'
    alias: Bedroom - Night light
    description: ''
    trigger:
    - platform: time
      at: '20:25:00'
    condition:
      - and:
        - condition: state
          entity_id: light.bedroom_lights
          state: 'off'
        - condition: numeric_state
          entity_id: sensor.bedroomplug_energy_power
          below: 30
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness_pct: 10
  - id: '1611015024885'
    alias: Bedroom - Left Button
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.double_switch_action
      to: single_left
    condition: []
    action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 10
    - service: light.turn_off
      data:
        entity_id: light.loungeroom_lights
    - service: light.turn_off
      data:
        entity_id: light.entry_lights
    - service: script.turn_on
      data:
        entity_id: script.turn_tv_lights_off
    mode: single
  - id: '1611015024886'
    alias: Bedroom - Right Button
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.double_switch_action
      to: single_right
    condition: []
    action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lights
    - service: light.turn_off
      data:
        entity_id: light.loungeroom_lights
    - service: light.turn_off
      data:
        entity_id: light.entry_lights
    - service: script.turn_on
      data:
        entity_id: script.turn_tv_lights_off
    - service: light.turn_off
      data:
        entity_id: light.bedroom_led
    mode: single
  - id: '1619755214062'
    alias: Bedroom - External Button
    description: ''
    trigger:
    - platform: device
      domain: mqtt
      device_id: 2ef7caaf49576189a87de78baf54888e
      type: action
      subtype: single
      discovery_id: 0x00158d00057316be action_single
    condition: []
    action:
    - service: light.toggle
      entity_id: light.bedroom_lights
    mode: single
  
