light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedroomdimmer

binary_sensor:
  - platform: mqtt
    name: RFremotebuttonA
    state_topic: 'tele/RFRemote/RESULT'
    value_template: >-
      {% if value_json.RfReceived.Data == 'B12201' %}
        {{'ON'}}
      {% else %}
        {{states('binary_sensor.rfremotebuttona') | upper}}
      {% endif %}
    off_delay: 5
  - platform: mqtt
    name: RFremotebuttonB
    state_topic: 'tele/RFRemote/RESULT'
    value_template: >-
      {% if value_json.RfReceived.Data == '361F01' %}
        {{'ON'}}
      {% else %}
        {{states('binary_sensor.rfremotebuttona') | upper}}
      {% endif %}
    off_delay: 5

automation:
  - id: '1610172763965'
    alias: Bedroom - Kid indicator on
    trigger:
    - platform: state
      entity_id: light.lucas_lights
    - platform: state
      entity_id: light.xander_lights
    condition: 
      condition: or
      conditions:
        - condition: state
          entity_id: light.lucas_lights
          state: 'on'
        - condition: state
          entity_id: light.xander_lights
          state: 'on'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_led
        brightness_pct: 40
        color_name: '{% if is_state(''light.lucas_lights'', ''on'') and is_state(''light.xander_lights'',
          ''on'') %} red {% elif is_state(''light.lucas_lights'', ''off'') and is_state(''light.xander_lights'',
          ''on'') %} green {% elif is_state(''light.lucas_lights'', ''on'') and is_state(''light.xander_lights'',
          ''off'') %} blue {% else %} black {% endif %}'
  - id: '1610172763966'
    alias: Bedroom - Kid indicator off
    trigger:
    - platform: state
      entity_id: light.lucas_lights
    - platform: state
      entity_id: light.xander_lights
    condition: 
      condition: and
      conditions:
        - condition: state
          entity_id: light.lucas_lights
          state: 'off'
        - condition: state
          entity_id: light.xander_lights
          state: 'off'
    action:
    - service: light.turn_off
      data_template:
        entity_id: light.bedroom_led
  - id: '1610190580265'
    alias: Bedroom - night light
    description: ''
    trigger:
    - platform: time
      at: '20:30:00'
    condition:
      - condition: state
        entity_id: light.bedroom_lights
        state: 'off'
    action:
    - service: light.turn_on
      data_template:
        entity_id: light.bedroom_lights
        brightness_pct: 10
  - id: '1611015024885'
    alias: Bedroom - Left Button
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.double_switch_click
      to: left
    condition: []
    action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness_pct: 10
    - service: light.turn_off
      data:
        entity_id: light.familyroom_lights
    - service: light.turn_off
      data:
        entity_id: light.entry_lights
    - service: script.turn_on
      data:
        entity_id: script.turn_tv_lights_off
    mode: single
  - id: '1611015024886'
    alias: Bedroom - Right Button
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.double_switch_click
      to: right
    condition: []
    action:
    - service: light.turn_off
      data:
        entity_id: light.bedroom_lights
    - service: light.turn_off
      data:
        entity_id: light.familyroom_lights
    - service: light.turn_off
      data:
        entity_id: light.entry_lights
    - service: script.turn_on
      data:
        entity_id: script.turn_tv_lights_off
    mode: single
