light:
  - platform: group
    name: Driveway Lights
    entities:
      - light.entrylight

automation:
  - id: '1618737848710'
    alias: Driveway - Front Door opened at night
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door_contact
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: "on"
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - delay:
        hours: 0
        minutes: 3
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1618649719654'
    alias: Driveway - person motion
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.driveway_person_motion
      from: 'off'
      to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: "on"
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.driveway_person_motion
        to: 'off'
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1618963905348'
    alias: Notify - Car Top
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_car_motion
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A car was detected
        data:
          image: /api/camera_proxy/camera.driveway_car
          actions:
            - action: URI
              title: "Open Camera"
              uri: https://frigate.adebenham.com/cameras/driveway
    - delay:
        minutes: 3
    mode: single
  - id: '1618963905350'
    alias: Notify - Car Top Yard
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_topyard_car_motion
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A car was detected
        data:
          image: /api/camera_proxy/camera.topyard_car
          actions:
            - action: URI
              title: "Open Camera"
              uri: https://frigate.adebenham.com/cameras/topyard
    - delay:
        minutes: 3
    mode: single
  - id: '1618963905349'
    alias: Notify - Person Top
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_person_motion
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A person was detected at the top of the driveway
        data:
          image: /api/camera_proxy/camera.driveway_person
          actions:
            - action: URI
              title: "Open Camera"
              uri: https://frigate.adebenham.com/cameras/driveway
    - delay:
        minutes: 5
    mode: single
  - id: '1618963905352'
    alias: Notify - Person Top Yard
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_yard_person_motion
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A person was detected at the top of the driveway
        data:
          image: /api/camera_proxy/camera.topyard_person
          actions:
            - action: URI
              title: "Open Camera"
              uri: https://frigate.adebenham.com/cameras/topyard
    - delay:
        minutes: 5
    mode: single
  - id: '1618964005086'
    alias: Notify - Person on Driveway
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.driveway_person_motion
      from: 'off'
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: time
        after: 08:30:00
        before: '15:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: time
        after: '20:00:00'
        before: 06:00:00
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A person is on the driveway
        data:
          image: /api/camera_proxy/camera.driveway_person
          actions:
            - action: URI
              title: "Open Camera"
              uri: https://frigate.adebenham.com/cameras/driveway
    - delay:
        minutes: 5
    mode: single
  - id: '1618649719675'
    alias: Driveway - Top of Driveway car motion
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_car_motion
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.night_mode
        state: "on"
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1619735738674'
    alias: Driveway - lights on when arriving home
    description: ''
    trigger:
    - platform: zone
      entity_id: person.chris
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: person.mel
      zone: zone.home
      event: enter
    condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: "on"
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - delay:
        minutes: 3
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart

  - alias: Notify
    trigger:
      - platform: state
        entity_id: sensor.double_take_driveway
      - platform: state
        entity_id: sensor.double_take_topyard
      - platform: state
        entity_id: sensor.double_take_unknown
    condition:
      - condition: template
        value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
    action:
      - service: notify.mobile_app
        data:
          message: |-
            {% if trigger.to_state.attributes.match is defined %}
              {{trigger.to_state.attributes.friendly_name}} is near the {{trigger.to_state.state}} @ {{trigger.to_state.attributes.match.confidence}}% by {{trigger.to_state.attributes.match.detector}}:{{trigger.to_state.attributes.match.type}} taking {{trigger.to_state.attributes.attempts}} attempt(s) @ {{trigger.to_state.attributes.duration}} sec
            {% elif trigger.to_state.attributes.unknown is defined %}
              unknown is near the {{trigger.to_state.state}} @ {{trigger.to_state.attributes.unknown.confidence}}% by {{trigger.to_state.attributes.unknown.detector}}:{{trigger.to_state.attributes.unknown.type}} taking {{trigger.to_state.attributes.attempts}} attempt(s) @ {{trigger.to_state.attributes.duration}} sec
            {% endif %}
          data:
            attachment:
              url: |-
                {% if trigger.to_state.attributes.match is defined %}
                  http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}
                {% elif trigger.to_state.attributes.unknown is defined %}
                  http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.unknown.filename}}?box=true&token={{trigger.to_state.attributes.token}}
                {% endif %}
            actions:
              - action: URI
                title: View Image
                uri: |-
                  {% if trigger.to_state.attributes.match is defined %}
                    http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.match.filename}}?box=true&token={{trigger.to_state.attributes.token}}
                  {% elif trigger.to_state.attributes.unknown is defined %}
                    http://localhost:3000/api/storage/matches/{{trigger.to_state.attributes.unknown.filename}}?box=true&token={{trigger.to_state.attributes.token}}
                  {% endif %}
    mode: parallel
    max: 10
