light:
  - platform: group
    name: Driveway Lights
    entities:
      - light.entrylight

automation:
  - id: '1618737848710'
    alias: Front Door opened at night
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door_sensor_contact
      from: 'off'
      to: 'on'
    condition:
    - condition: sun
      after: sunset
      after_offset: -01:00:00
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1618649719644'
    alias: Motion - Driveway person
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.driveway_person_motion
      from: 'off'
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
        before_offset: '-1:00:00'
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.driveway_person_motion
        to: 'off'
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1618649719648'
    alias: Notify of events
    trigger:
      platform: mqtt
      topic: frigate/events
    action:
      - service: notify.mobile_app_chrisphone
        data_template:
          message: 'A {{trigger.payload_json["after"]["label"]}} was detected.'
          data:
            image: 'https://ha.adebenham.com/api/frigate/notifications/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg?format=android'
            tag: '{{trigger.payload_json["after"]["id"]}}'
