light:
  - platform: group
    name: Driveway Lights
    entities:
      - light.entrylight

automation:
  - id: '1618737848710'
    alias: Driveway - Front Door opened at night
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.front_door_sensor_contact
      from: 'off'
      to: 'on'
    condition:
    - condition: sun
      after: sunset
      after_offset: -01:00:00
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - delay:
        hours: 0
        minutes: 1
        seconds: 0
        milliseconds: 0
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1618649719644'
    alias: Motion - Driveway person
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.driveway_person_motion
      from: 'off'
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
        before_offset: '-1:00:00'
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.driveway_person_motion
        to: 'off'
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
  - id: '1618963905348'
    alias: Notify - Car
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_car_motion
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A car was detected
        data:
          image: /api/camera_proxy/camera.driveway_car
    mode: single
  - id: '1618964005086'
    alias: Notify - Person on Driveway
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.driveway_person_motion
      from: 'off'
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: time
        after: 08:30:00
        before: '15:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: time
        after: '20:00:00'
        before: 06:00:00
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: A person is on the driveway
        data:
          image: /api/camera_proxy/camera.driveway_person
    mode: single
  - id: '1618649719645'
    alias: Motion - Top of Driveway car
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.top_of_driveway_car_motion
      from: 'off'
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
        before_offset: '-1:00:00'
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
    action:
    - service: light.turn_on
      entity_id: light.driveway_lights
    - delay:
        minutes: 3
    - service: light.turn_off
      entity_id: light.driveway_lights
    mode: restart
