light:
  - platform: template
    lights:
      garage_lights:
        friendly_name: Garage Lights
        value_template: >-
          {% if is_state('light.garage_left','on') or is_state('light.garage_right', 'on') %}
            on
          {% else %}
            off
          {% endif %}
        level_template: >-
          {% if is_state('light.garage_left','on') and is_state('light.garage_right', 'on') %}
            255
          {% elif is_state('light.garage_left','on') and is_state('light.garage_right', 'off') %}
            170
          {% elif is_state('light.garage_left','off') and is_state('light.garage_right', 'on') %}
            85
          {% else %}
            0
          {% endif %}
        turn_on:
          - service: light.turn_on
            entity_id: light.garage_left
          - service: light.turn_on
            entity_id: light.garage_right
        turn_off:
          - service: light.turn_off
            entity_id: light.garage_left
          - service: light.turn_off
            entity_id: light.garage_right
        set_level:
          - service: light.turn_on
            entity_id: light.garage_right
            data:
              brightness: >-
                {% if ((brightness > 0) and (brightness <= 85)) or (brightness>170)%}255{%else%}0{%endif%}
          - service: light.turn_on
            entity_id: light.garage_left
            data:
              brightness: >-
                {% if brightness > 85 %}255{%else%}0{%endif%}

template:
  - binary_sensor:
      - name: "GaragePlug Running"
        state: "{{ states('sensor.garageplug_energy_power') | float(0) > 40 }}"
        delay_on: "0:00:10"
        delay_off: "0:00:10"
  - sensor:
    - name: "Garage Wattage"
      unit_of_measurement: W
      state_class: measurement
      device_class: energy
      state: "{{ states('sensor.garageplug_energy_power')|float(0)
               + states('sensor.garage_left_power')|float(0)
               + states('sensor.garage_right_power')|float(0) }}"

binary_sensor:
  - platform: template
    sensors:
      outback_presence:
        friendly_name: "Outback Presence"
        device_class: presence
        value_template: "{{ is_state('input_boolean.outback_home', 'on') }}"
      impreza_presence:
        friendly_name: "Impreza Presence"
        device_class: presence
        value_template: "{{ is_state('input_boolean.impreza_home', 'on') }}"

timer:
  garage_mcl:
    duration: '00:00:10'

input_boolean:
  garage_mcl:
    name: Motion-Controlled Garage Light
    initial: true
  outback_home:
    name: Outback presence input
    initial: false
  impreza_home:
    name: Impreza presence input
    initial: false

automation:
  - id: '1642994206210'
    alias: Garage - Open/Close Garage door
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.garage_right_input
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: cover.toggle
      target:
        entity_id: cover.garage_door
    mode: single
  - id: '1642994206211'
    alias: Garage - Sync Pair
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.garage_left_input
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_left_input
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: >-
        {% if is_state('light.garage_left', 'on') %}
        light.turn_on
        {% else %}
        light.turn_off
        {% endif %}
      entity_id: light.garage_right
    mode: single
  - id: '1640563153177'
    alias: Notify - Garage Left Open
    description: ''
    trigger:
    - platform: state
      entity_id: light.bedroom_lights
      from: 'on'
      to: 'off'
    condition:
    - condition: time
      after: '20:00:00'
    - condition: state
      entity_id: cover.garage_door
      state: open
    action:
    - service: tts.google_translate_say
      data:
        entity_id: media_player.chris_clock
        message: The garage door is open
    mode: single
  - id: '1627699444400'
    alias: Notify - Outback home
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.outback_presence
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: Outback is home
    mode: single
  - id: '1628117617684'
    alias: Car - Set outback away
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.outback
      to: 'off'
      for: 0:30:00
    condition: []
    action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.outback_home
    mode: single
  - id: '1628117617685'
    alias: Car - Set outback home
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.outback
      to: 'on'
    condition: []
    action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.outback_home
    mode: single
  - id: '1627699444401'
    alias: Notify - Impreza home
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.impreza_presence
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: Impreza is home
    mode: single
  - id: '1628117617686'
    alias: Car - Set Impreza away
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.impreza
      to: 'off'
      for: 0:30:00
    condition: []
    action:
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.impreza_home
    mode: single
  - id: '1628117617687'
    alias: Car - Set Impreza home
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.impreza
      to: 'on'
    condition: []
    action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.impreza_home
    mode: single
  - id: '1618649719643'
    alias: Garage - Light Auto-on
    trigger:
    - platform: state
      entity_id: binary_sensor.garage_person_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_sensor_contact
      from: 'off'
      to: 'on'
    condition:
      - and:
        - condition: state
          entity_id: input_boolean.night_mode
          state: 'on'
        - condition: state
          entity_id: light.garage_lights
          state: 'off'
        - condition: template
          value_template: "{{ is_state('input_boolean.garage_mcl', 'on') }}"
    action:
    - service: light.turn_on
      entity_id: light.garage_lights
    mode: restart
  - id: '1618649719644'
    alias: Garage - Light Auto-off
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_person_motion
        to: 'off'
        for: '00:03:00'
      - platform: state
        entity_id: binary_sensor.door_sensor_contact
        from: 'on'
        to: 'off'
    condition:
      - condition: template
        value_template: "{{ is_state('input_boolean.garage_mcl', 'on') }}"
    action:
      service: light.turn_off
      entity_id: light.garage_lights
  - id: '1618649719645'
    alias: Garage - Light manual off
    trigger:
      platform: state
      entity_id: light.garage_lights
      from: 'on'
      to: 'off'
    action:
      service: timer.start
      entity_id: timer.garage_mcl
  - id: '1618649719646'
    alias: Garage - Light manual on
    trigger:
      platform: state
      entity_id: light.garage_lights
      from: 'off'
      to: 'on'
    condition:
      - condition: template
        value_template: "{{ is_state('timer.garage_mcl', 'active') }}"
    action:
      service: input_boolean.toggle
      entity_id: input_boolean.garage_mcl
  - id: '1618649719647'
    alias: Garage - Light MCL Re-Enable
    trigger:
      platform: state
      entity_id: input_boolean.garage_mcl
      to: 'off'
      for: '01:00:00'
    action:
      service: input_boolean.turn_on
      entity_id: input_boolean.garage_mcl
  - id: '1618977583813'
    alias: Cameras - Turn On Garage recording at night or when away
    description: ''
    trigger:
    - platform: time
      at: '19:00:00'
    - platform: state
      entity_id: person.chris
      to: not_home
    - platform: state
      entity_id: person.mel
      to: not_home
    condition:
    - or:
      - condition: time
        after: '19:00:00'
      - and:
        - condition: state
          entity_id: person.chris
          state: not_home
        - condition: state
          entity_id: person.mel
          state: not_home
    action:
    - service: switch.turn_on
      entity_id: switch.garage_recordings
    mode: single
  - id: '1618978148074'
    alias: Cameras - Turn Off Garage recording when home
    description: ''
    trigger:
    - platform: state
      entity_id: person.chris
      to: home
    - platform: state
      entity_id: person.mel
      to: home
    - platform: time
      at: 08:00:00
    condition:
    - or:
      - condition: state
        entity_id: person.chris
        state: home
      - condition: state
        entity_id: person.mel
        state: home
    action:
    - service: switch.turn_off
      entity_id: switch.garage_recordings
    mode: single
  - id: '1639524461025'
    alias: Garage - Charger finished
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.garageplug_running
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: Garage charger finished
    mode: single