light:
  - platform: group
    name: Garage Lights
    entities:
      - light.garage_left
      - light.garage_right

binary_sensor:
  - platform: mqtt
    name: Garage Entry Open
    state_topic: 'tele/RFRemote/RESULT'
    value_template: >-
      {% if value_json.RfReceived.Data == '372DF6' %}
        {{'ON'}}
      {% else %}
        {{states('binary_sensor.rfremotebuttona') | upper}}
      {% endif %}
    off_delay: 5

automation:
  - id: '1618649719643'
    alias: Motion - Garage person
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.garage_person_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.garage_entry_open
      from: 'off'
      to: 'on'
    condition:
    - condition: or
      conditions:
      - condition: sun
        before: sunrise
        before_offset: '-1:00:00'
      - condition: sun
        after: sunset
        after_offset: '-1:00:00'
    action:
    - service: light.turn_on
      entity_id: light.garage_lights
    - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.garage_person_motion
        to: 'off'
    - service: light.turn_off
      entity_id: light.garage_lights
    mode: restart
  - id: '1618977583813'
    alias: Cameras - Turn On Garage recording at night or when away
    description: ''
    trigger:
    - platform: time
      at: '19:00:00'
    - platform: state
      entity_id: person.chris
      to: not_home
    - platform: state
      entity_id: person.mel
      to: not_home
    condition:
    - condition: or
      conditions:
      - condition: time
        after: '19:00:00'
      - condition: and
        conditions:
        - condition: state
          entity_id: person.chris
          state: not_home
        - condition: state
          entity_id: person.mel
          state: not_home
    action:
    - service: switch.turn_on
      entity_id: switch.garage_clips
    mode: single
  - id: '1618978148074'
    alias: Cameras - Turn Off Garage recording when home
    description: ''
    trigger:
    - platform: state
      entity_id: person.chris
      to: home
    - platform: state
      entity_id: person.mel
      to: home
    - platform: time
      at: 08:00:00
    condition:
    - condition: or
      conditions:
      - condition: state
        entity_id: person.chris
        state: home
      - condition: state
        entity_id: person.mel
        state: home
    action:
    - service: switch.turn_off
      entity_id: switch.garage_clips
    mode: single
  