light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchenfront
      - light.kitchenback

automation:
  - id: '1615539466617'
    alias: Kitchen - Turn on strip when the sun is set
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.entry_sensor_illuminance_lux
        below: 200
        for: "00:05:00"
    condition: []
    action:
      - service: light.turn_on
        entity_id: light.kitchen_strip
        data:
          brightness_pct: 50
          effect: Cycle
    mode: single
  - id: '1615539466618'
    alias: Kitchen - Turn off strip when the sun is up
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.entry_sensor_illuminance_lux
        above: 200
        for: "00:15:00"
    condition: []
    action:
      - service: light.turn_off
        entity_id: light.kitchen_strip
    mode: single
