light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchenfront
      - light.kitchenback

template:
  - binary_sensor:
      - name: "Dishwasher Running"
        state: "{{ states('sensor.dishwasher_energy_power') | float(0) > 5 }}"
        delay_on: "0:00:30"
        delay_off: "0:00:30"

automation:
  - id: '1615539466617'
    alias: Kitchen - Turn on strip when the sun is set
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.night_mode
        to: "on"
    condition: []
    action:
      - service: light.turn_on
        entity_id: light.kitchen_strip
        data:
          brightness_pct: 50
          effect: Cycle
    mode: single
  - id: '1615539466618'
    alias: Kitchen - Turn off strip when the sun is up
    description: ''
    trigger:
      - platform: state
        entity_id: input_boolean.night_mode
        to: "off"
    condition: []
    action:
      - service: light.turn_off
        entity_id: light.kitchen_strip
    mode: single
  - id: '1630278899301'
    alias: Notify - Dishwasher Finished
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.dishwasher_running
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: Dishwasher finished
    mode: single