group:
  loungeroom_lightgroup:
    name: Loungeroom Light Group
    entities:
      - light.lounge_bl
      - light.lounge_br
      - light.lounge_ml
      - light.lounge_mr
      - light.lounge_fl
      - light.lounge_fr

light:
  - platform: group
    name: loungeroom Lights
    entities:
      - light.lounge_bl
      - light.lounge_br
      - light.lounge_ml
      - light.lounge_mr
      - light.lounge_fl
      - light.lounge_fr
  - platform: template
    lights:
      backlight_switch:
        friendly_name: "TV Backlight"
        value_template: "{{ is_state('light.tvbacklight', 'on') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.turn_tv_lights_on
        turn_off:
          service: script.turn_on
          entity_id: script.turn_tv_lights_off

switch:
  - platform: template
    switches:
      loungeroom_normal:
        friendly_name: "Loungeroom Full"
        value_template: >
          {% if states('light.lounge_ml') %}
            {% if state_attr('light.lounge_ml','brightness')|int(0) == 255 %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        turn_on:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_normal
        turn_off:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_off
      loungeroom_low:
        friendly_name: "Loungeroom Medium"
        value_template: >
          {% if states('light.lounge_ml') %}
            {% if ((state_attr('light.lounge_ml','brightness')|int(0) > 100) and (state_attr('light.lounge_ml','brightness')|int(0) < 200)) %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        turn_on:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_low
        turn_off:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_off
      loungeroom_dim:
        friendly_name: "Loungeroom Dim"
        value_template: >
          {% if states('light.lounge_ml') %}
            {% if ((state_attr('light.lounge_ml','brightness')|int(0) < 100) and (state_attr('light.lounge_ml','brightness')|int(0) > 0)) %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        turn_on:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_dim
        turn_off:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_off
      loungeroom_party:
        friendly_name: "Loungeroom Party"
        value_template: >
          {% if states('light.lounge_ml') %}
            {% if ((state_attr('light.lounge_ml','brightness')|int(0) < 100) and (state_attr('light.lounge_ml','brightness')|int(0) > 0)) %}
              true
            {% else %}
              false
            {% endif %}
          {% else %}
            false
          {% endif %}
        turn_on:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_party
        turn_off:
          service: scene.turn_on
          target:
            entity_id: scene.loungeroom_off
  - platform: mqtt
    name: "Loungeroom Blind Motor Direction"
    icon: mdi:blinds
    state_topic: "tele/LoungeroomBlind/RESULT"
    state_on: 1
    state_off: 0
    value_template: >-
        {% if value_json['TuyaReceived'].DpType1Id5 is defined %}
        {{ value_json.TuyaReceived.DpType1Id5 }}
        {% else %}  
        {{ states('switch.motor_direction') }}
        {% endif %}  
    command_topic: "cmnd/LoungeroomBlind/TuyaSend"
    payload_on: "5,1"
    payload_off: "5,0"
    availability_topic: "tele/LoungeroomBlind/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"


cover:
  - platform: mqtt
    # requires SetOption59 1, TuyaMCU 21,2
    name: "Loungeroom Blind"
    device_class: shade 
    command_topic: "cmnd/LoungeroomBlind/TuyaSend4"
    payload_open: "1,0"
    payload_close: "1,2"
    payload_stop: "1,1"
    position_open: 0
    position_closed: 100
    position_topic: "tele/LoungeroomBlind/STATE"
    position_template: '{{ value_json.Dimmer }}'
    set_position_topic: "cmnd/LoungeroomBlind/Dimmer"
    set_position_template: '{{ 100 - position | int }}'
    availability_topic: "tele/LoungeroomBlind/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

binary_sensor:
- platform: mqtt
  name: "Loungeroom Blind Motor Error"
  state_topic: "tele/LoungeroomBlind/RESULT"
  device_class: problem
  value_template: >-
      {% if value_json.TuyaReceived.DpType5Id10 is defined %}      
        {% if value_json.TuyaReceived.DpType5Id10  == '0x00' %}      
        OFF
        {% else %}
        ON
        {% endif %}
      {% else %}
      OFF
      {% endif %}

automation:
  - id: '1613520733142'
    alias: Loungeroom - Party Mode
    description: ''
    trigger:
    - platform: state
      entity_id: switch.loungeroom_relay_2
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: switch.loungeroom_relay_2
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: scene.turn_on
      entity_id: scene.loungeroom_party
    mode: single
  - id: '1613520733143'
    alias: Loungeroom - Switch 1
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.loungeroom_switch1
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: switch.toggle
      entity_id: switch.loungeroom_dim
    mode: single
  - id: '1613520733144'
    alias: Loungeroom - Switch 2
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.loungeroom_switch2
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: switch.toggle
      entity_id: switch.loungeroom_low
    mode: single
  - id: '1613520733145'
    alias: Loungeroom - Switch 3
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.loungeroom_switch3
      from: 'off'
      to: 'on'
    condition: []
    action:
    - service: switch.toggle
      entity_id: switch.loungeroom_normal
    mode: single
  - id: '1610429484473'
    alias: Lounge room - light strip on in evening
    description: ''
    trigger:
    - platform: time
      at: '18:00:00'
    condition: []
    action:
    - service: light.turn_on
      data:
        entity_id: light.loungeroomstrip_master
    - service: select.select_option
      target:
        entity_id: select.loungeroomstrip_preset
      data:
        option: Default
    mode: single
  - id: '1610429484474'
    alias: Lounge room - light strip off at night
    description: ''
    trigger:
    - platform: time
      at: '23:00:00'
    condition: []
    action:
    - service: light.turn_off
      entity_id: light.loungeroomstrip_master
    mode: single
  - id: '1610430895471'
    alias: Loungeroom - Outside Switch - lights on
    trigger:
    - platform: state
      entity_id: binary_sensor.loungeroomdimmer_channel_1_input
      from:
        - 'on'
        - 'off'
      to:
        - 'on'
        - 'off'
    condition: 
      - condition: state
        entity_id: light.loungeroom_lights
        state: 'on'
    action:
      - service: scene.turn_on
        entity_id: scene.loungeroom_off
  - id: '1610430895472'
    alias: Loungeroom - Outside Switch - lights off
    trigger:
    - platform: state
      entity_id: binary_sensor.loungeroomdimmer_channel_1_input
      from:
        - 'on'
        - 'off'
      to:
        - 'on'
        - 'off'
    condition: 
      - condition: state
        entity_id: light.loungeroom_lights
        state: 'off'
    action:
      - service: scene.turn_on
        entity_id: scene.loungeroom_low
  - id: '1623134323431'
    alias: Blinds - Open at sunrise
    description: ''
    trigger:
    - platform: sun
      event: sunrise
    condition: []
    action:
    - service: cover.stop_cover
      target:
        entity_id: cover.loungeroom_blind
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: cover.open_cover
      target:
        entity_id: cover.loungeroom_blind
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: cover.set_cover_position
      data:
        position: 99
      target:
        entity_id: cover.loungeroom_blind
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: cover.set_cover_position
      target:
        entity_id: cover.loungeroom_blind
      data:
        position: 100
    mode: single
  - id: '1623134374989'
    alias: Blinds - Close 1hr after sunset
    description: ''
    trigger:
    - platform: sun
      event: sunset
      offset: '1:00:00'
    condition: []
    action:
    - service: cover.stop_cover
      target:
        entity_id: cover.loungeroom_blind
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: cover.close_cover
      target:
        entity_id: cover.loungeroom_blind
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: cover.set_cover_position
      target:
        entity_id: cover.loungeroom_blind
      data:
        position: 1
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: cover.set_cover_position
      data:
        position: 0
    mode: single


script:
  turn_tv_lights_on:
    mode: restart
    sequence:
      - service: light.turn_on
        entity_id: light.tvbacklight
      - service: select.select_option
        target:
          entity_id: select.tvbacklight_preset
        data:
          option: Default
      - service: light.turn_on
        entity_id: light.loungeroomstrip_master
      - service: select.select_option
        target:
          entity_id: select.loungeroomstrip_preset
        data:
          option: Default
  turn_tv_lights_off:
    mode: restart
    sequence:
      - service: light.turn_off
        entity_id: light.tvbacklight
      - service: light.turn_off
        entity_id: light.loungeroomstrip_master

scene:
  - id: '1611195993245'
    name: Watching TV
    entities:
      light.tvbacklight:
        state: "on"
      light.tvbacklight_preset:
        state: Default
      light.loungeroomstrip_master:
        state: "on"
      select.loungeroomstrip_preset:
        state: Default
    icon: mdi:television-ambient-light
  - id: '1611195993246'
    name: Not Watching TV
    entities:
      light.tvbacklight:
        state: "off"
      light.loungeroomstrip_master:
        state: "off"
    icon: mdi:television
  - id: '1613889672194'
    name: Loungeroom Normal
    icon: mdi:sofa
    entities:
      light.loungeroom_lights:
        brightness: 255
        color_temp: 402
        effect: None
        state: 'on'
      light.tvbacklight:
        state: 'on'
      light.tvbacklight_preset:
        state: Default
      light.loungeroomstrip_master:
        state: "on"
      select.loungeroomstrip_preset:
        state: Default
  - id: '1613889765919'
    name: Loungeroom Dim
    entities:
      light.lounge_bl:
        state: 'off'
      light.lounge_br:
        state: 'off'
      light.lounge_fl:
        state: 'off'
      light.lounge_fr:
        state: 'off'
      light.lounge_ml:
        brightness: 70
        color_temp: 402
        effect: None
        state: 'on'
      light.lounge_mr:
        brightness: 70
        color_temp: 402
        effect: None
        state: 'on'
      light.loungeroomstrip_master:
        state: "on"
      select.loungeroomstrip_preset:
        state: Default
      light.tvbacklight:
        state: 'on'
      light.tvbacklight_preset:
        state: Default
  - id: '1613889879080'
    name: Loungeroom Off
    entities:
      light.loungeroomstrip_master:
        state: 'off'
      light.loungeroom_lights:
        state: 'off'
      light.tvbacklight:
        state: 'off'
  - id: '1614067231868'
    name: Loungeroom Low
    entities:
      light.tvbacklight:
        state: 'on'
      light.tvbacklight_preset:
        state: Default
      light.loungeroomstrip_master:
        state: "on"
      select.loungeroomstrip_preset:
        state: Default
      light.loungeroom_lights:
        brightness: 150
        color_temp: 402
        effect: None
        state: 'on'
  - id: '1614067231869'
    name: Loungeroom Party
    icon: mdi:party-popper
    entities:
      light.tvbacklight:
        state: 'on'
      light.tvbacklight_preset:
        state: 'Party'
      light.loungeroomstrip_master:
        state: "on"
      select.loungeroomstrip_preset:
        state: 'Party'
      light.loungeroom_lights:
        brightness: 255
        rgb_color: [0,0,255]
        effect: Random
        state: 'on'