light:
  - platform: group
    name: Office Lights
    entities:
      - light.officedimmer

template:
  - sensor:
    - name: "Office Wattage"
      unit_of_measurement: W
      state_class: measurement
      device_class: energy
      state: "{{ states('sensor.desk_energy_power')|float(0)
               + states('sensor.officedimmer_power')|float(0)
               + states('sensor.serverstack_energy_power')|float(0)}}"

automation:
  - id: '1648014715445'
    alias: Notify - Printing Finished
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.octoprint_current_state
      from: 'Printing'
      to: 'Operational'
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: 3D Printer finished
        actions:
          - action: TURN_OFF_3DPRINTER
            title: "Turn off 3D Printer"
    mode: single
  - alias: Notify - Handle 3D Printer action
    trigger:
      platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: TURN_OFF_3DPRINTER
    condition: []
    action:
    - service: switch.turn_off
      entity_id: switch.3dprinter
  - id: '1610484353901'
    alias: Office - Switch 1
    trigger:
      - entity_id: binary_sensor.office_switch1
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        entity_id: light.office_strip
        data:
          effect: Rainbow
      - service: light.turn_on
        entity_id: light.asrock_b550_pro4_0
        data:
          effect: 'Rainbow'
  - id: '1610484353902'
    alias: Office - Switch 2
    trigger:
      - entity_id: binary_sensor.office_switch2
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: switch.turn_on
        entity_id: switch.powerboard3_outlet_1
      - service: switch.turn_on
        entity_id: switch.powerboard3_outlet_2
      - service: switch.turn_on
        entity_id: switch.powerboard3_outlet_4
  - id: '1610484353903'
    alias: Office - Switch 3
    trigger:
      - entity_id: binary_sensor.office_switch3
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: switch.turn_off
        entity_id: switch.powerboard3_outlet_1
      - service: switch.turn_off
        entity_id: switch.powerboard3_outlet_2
      - service: switch.turn_off
        entity_id: switch.powerboard3_outlet_4
      - service: light.turn_off
        entity_id: light.office_strip
      - service: light.turn_off
        entity_id: light.office_lights
      - service: light.turn_on
        entity_id: light.asrock_b550_pro4_0
        data:
          effect: 'Off'
  - id: '1620696771165'
    alias: Spinnner Brightness Down
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.spinner_action
      to: rotate_left
    condition: []
    action:
    - service: light.turn_on
      target:
        entity_id: light.office_lights
      data:
        brightness_step_pct: -5
    mode: single
  - id: '1620696771166'
    alias: Spinnner Brightness Up
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.spinner_action
      to: rotate_right
    condition: []
    action:
    - service: light.turn_on
      target:
        entity_id: light.office_lights
      data:
        brightness_step_pct: 5
    mode: single
  - id: '1620696771167'
    alias: Spinnner Press
    description: ''
    trigger:
    - platform: state
      entity_id: sensor.spinner_action
      to: play_pause
    condition: []
    action:
    - service: light.toggle
      target:
        entity_id: light.office_lights
    mode: single
  - id: '1658097701179'
    alias: Notify - Doorbell Pressed
    description: ''
    trigger:
    - platform: device
      device_id: 3243b58136136f6fa25f1f022e85b478
      domain: nest
      type: doorbell_chime
    condition: []
    action:
    - service: notify.mobile_app_chrisphone
      data:
        message: Someone at the door
    mode: single
  - id: '1658282850142'
    alias: Office - Doorbell
    description: ''
    trigger:
    - platform: state
      entity_id:
      - sensor.officedoor_action
      to: single
    condition: []
    action:
    - service: media_player.play_media
      target:
        entity_id: media_player.office_speaker
      data:
        media_content_id: media-source://media_source/local/THERES SOMEBODY AT THE DOOR.mp3
        media_content_type: audio/mpeg
      metadata:
        title: THERES SOMEBODY AT THE DOOR.mp3
        thumbnail:
        media_class: music
        children_media_class:
        navigateIds:
        - {}
        - media_content_type: app
          media_content_id: media-source://media_source
    mode: single
