light:
  - platform: group
    name: Office Lights
    entities:
      - light.officedimmer

automation:
  - alias: Office - Switch 1
    trigger:
      - entity_id: binary_sensor.office_switch1
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        entity_id: light.office_strip
        data:
          effect: Rainbow
  - alias: Office - Switch 2
    trigger:
      - entity_id: binary_sensor.office_switch2
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: switch.turn_on
        entity_id: switch.powerboard3_outlet_1
      - service: switch.turn_on
        entity_id: switch.powerboard3_outlet_2
      - service: switch.turn_on
        entity_id: switch.powerboard3_outlet_4
  - alias: Office - Switch 3
    trigger:
      - entity_id: binary_sensor.office_switch3
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: switch.turn_off
        entity_id: switch.powerboard3_outlet_1
      - service: switch.turn_off
        entity_id: switch.powerboard3_outlet_2
      - service: switch.turn_off
        entity_id: switch.powerboard3_outlet_4
      - service: light.turn_off
        entity_id: light.office_strip
      - service: light.turn_off
        entity_id: light.office_lights
