light:
  - platform: group
    name: Xander Lights
    entities:
      - light.xanderdimmer

automation:
  - id: moon_on
    alias: Xander - Moon - turn on
    trigger:
      platform: time
      at: "18:00:00"
    action:
      service: light.turn_on
      data:
        entity_id: light.moon_led
        effect: Slow Random Effect
  - id: moon_off
    alias: Xander - Moon - turn off
    trigger:
      platform: time
      at: "07:00:00"
    action:
      service: light.turn_off
      data:
        entity_id: light.moon_led
