light:
  - platform: group
    name: Deck Lights
    entities:
      - light.deck
      - light.kitchendoor

automation:
  # - id: '1615539466627'
  #   alias: Deck - Turn on spotlights when the sun is set
  #   description: ''
  #   trigger:
  #     - platform: state
  #       entity_id: input_boolean.night_mode
  #       to: "on"
  #   condition: []
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.gardenlights
  #       data:
  #         brightness_pct: 50
  #         effect: Cycle
  #   mode: single
  # - id: '1615539466628'
  #   alias: Deck - Turn off spotlights when the sun is up
  #   description: ''
  #   trigger:
  #     - platform: state
  #       entity_id: input_boolean.night_mode
  #       to: "off"
  #   condition: []
  #   action:
  #     - service: light.turn_off
  #       entity_id: light.gardenlights
  #   mode: single

fan:
  - platform: mqtt
    name: "Deck Fan"
    unique_id: master_bedroom_fan
    command_topic: "cmnd/deckfan/tasmota_55DA72/POWER2"
    state_topic: "stat/deckfan/tasmota_55DA72/POWER2"
    preset_mode_command_topic: "cmnd/deckfan/tasmota_55DA72/Backlog"
    preset_mode_command_template: >
      {% if value == 'low' %}
        Event s=1
      {% elif value == 'medium' %}
        Event s=2
      {% elif value == 'high' %}
        Event s=3
      {% endif %}
    preset_mode_state_topic: "stat/deckfan/tasmota_55DA72/fanspeed"
    preset_mode_value_template: >
      {% if value == '2' %}
        high
      {% elif value == '1' %}
        medium
      {% elif value == '3' %}
        low
      {% endif %}
    availability_topic: "tele/deckfan/tasmota_55DA72/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    preset_modes:
      - 'low'
      - 'medium'
      - 'high'