- alias: Dimmer - Backroom
  trigger:
  - entity_id: sensor.backroom_dimmer_action
    platform: state
  condition: []
  action:
  - entity_id: light.backroom_light_group
    service_template: >
        {% if trigger.to_state.state|length %}light.turn_on
        {% else %}script.noop
        {% endif %}
    data_template:
      transition: 2
      brightness_pct: >
        {% if trigger.to_state.state == 'on-press' %} 100
        {% elif trigger.to_state.state == 'up-press' %} 50
        {% elif trigger.to_state.state == 'down-press' %} 1
        {% elif trigger.to_state.state == 'off-press' %} 0
        {% endif %}
