- alias: Backroom Switch1
  trigger:
  - entity_id: binary_sensor.backroom_switch1
    platform: state
    to: 'on'
  action:
  - entity_id: light.backroom_light_group
    service: light.turn_on
    data_template:
      transition: 1
      brightness_pct: 100
- alias: Backroom Switch2
  trigger:
  - entity_id: binary_sensor.backroom_switch2
    platform: state
    to: 'on'
  action:
  - entity_id: switch.backroom_relay_1
    service: switch.turn_on
- alias: Backroom Switch3
  trigger:
  - entity_id: binary_sensor.backroom_switch3
    platform: state
    to: 'on'
  action:
  - entity_id: light.backroom_light_group
    service: light.turn_off
  - entity_id: switch.backroom_relay_1
    service: switch.turn_off
