- id: kids_lights
  alias: Main bedroom - Kid indicator
  trigger:
    - platform: state
      entity_id: group.lucas_bedroom_lights
    - platform: state
      entity_id: group.xander_bedroom_lights
  condition: []
  action:
    service: light.turn_on
    data_template:
      entity_id: light.bedroom_led
      brightness_pct: "{% if is_state('group.lucas_bedroom_lights', 'off') and is_state('group.xander_bedroom_lights', 'off') %}0{% else %}100{% endif %}"
      color_name: >
        {% if is_state('group.lucas_bedroom_lights', 'on') and is_state('group.xander_bedroom_lights', 'on') %} red
        {% elif is_state('group.lucas_bedroom_lights', 'off') and is_state('group.xander_bedroom_lights', 'on') %} green
        {% elif is_state('group.lucas_bedroom_lights', 'on') and is_state('group.xander_bedroom_lights', 'off') %} blue
        {% else %} white
        {% endif %}
- id: main_bedroom_night_mode
  alias: Main bedroom night mode
  trigger:
    platform: time
    at: '20:30:00'
  condition:
    condition: state
    entity_id: group.bedroom_lights
    state: 'off'
  action:
    service: light.turn_on
    data:
      entity_id: group.bedroom_lights
      brightness_pct: 50
      transition: 300
- alias: Main Bedroom light on
  trigger:
  - entity_id: sensor.main_bedroom_dimmer_action
    platform: state
    to: 'on-press'
  condition: []
  action:
  - entity_id: group.bedroom_lights
    service: light.turn_on
    data:
      brightness_pct: 100
- alias: Main Bedroom light up press
  trigger:
  - entity_id: sensor.main_bedroom_dimmer_action
    platform: state
    to: 'up-press'
  condition: []
  action:
  - entity_id: group.bedroom_lights
    service: light.turn_on
    data:
       brightness_pct: 50
- alias: Main Bedroom light down press
  trigger:
  - entity_id: sensor.main_bedroom_dimmer_action
    platform: state
    to: 'down-press'
  condition: []
  action:
  - entity_id: group.bedroom_lights
    service: light.turn_on
    data:
      brightness_pct: 10
- alias: Main Bedroom light off
  trigger:
  - entity_id: sensor.main_bedroom_dimmer_action
    platform: state
    to: 'off-press'
  condition: []
  action:
  - entity_id: group.bedroom_lights
    service: light.turn_off
