- alias: Dimmer - Entry
  trigger:
  - entity_id: sensor.entry_dimmer_action
    platform: state
  condition: []
  action:
    - entity_id: light.bulb_white_3
      service_template: >
        {% if trigger.to_state.state == 'on-press' %}light.turn_on
        {% elif trigger.to_state.state == 'up-press' %}script.noop
        {% elif trigger.to_state.state == 'down-press' %}light.turn_off
        {% elif trigger.to_state.state == 'off-press' %}light.turn_off
        {% else %}script.noop
        {% endif %}
      data:
        transition: 0
    - entity_id: light.sensor_light
      service_template: >
        {% if trigger.to_state.state == 'on-press' %}script.noop
        {% elif trigger.to_state.state == 'up-press' %}light.turn_on
        {% elif trigger.to_state.state == 'down-press' %}script.noop
        {% elif trigger.to_state.state == 'off-press' %}light.turn_off
        {% else %}script.noop
        {% endif %}
      data:
        transition: 0
    - entity_id: light.bulb_colour_3
      service_template: >
        {% if trigger.to_state.state == 'on-press' %}light.turn_on
        {% elif trigger.to_state.state == 'up-press' %}script.noop
        {% elif trigger.to_state.state == 'down-press' %}light.turn_on
        {% elif trigger.to_state.state == 'off-press' %}light.turn_on
        {% else %}script.noop
        {% endif %}
      data_template:
        transition: 0
        color_name: blue
        brightness_pct: >
          {% if trigger.to_state.state == 'down-press' %}100
          {% else %}0
          {% endif %}
