- alias: Entry - Switch1
  trigger:
  - entity_id: binary_sensor.entry_switch1
    platform: state
    to: 'on'
  action:
    - entity_id: light.bulb_white_3
      service: light.turn_on
      data:
        transition: 0
        brightness_pct: 100
    - entity_id: light.bulb_colour_3
      service: light.turn_off
- alias: Entry - Switch2
  trigger:
  - entity_id: binary_sensor.entry_switch2
    platform: state
    to: 'on'
  action:
    - entity_id: light.sensor_light
      service: light.turn_on
      data:
        transition: 0
        brightness_pct: 100
- alias: Entry - Switch3
  trigger:
  - entity_id: binary_sensor.entry_switch3
    platform: state
    to: 'on'
  action:
    - entity_id: light.bulb_white_3
      service: light.turn_off
    - entity_id: light.bulb_colour_3
      service: light.turn_off
    - entity_id: light.sensor_light
      service: light.turn_off
    
