- alias: Hall Switch1
  trigger:
  - entity_id: binary_sensor.hallway_switch1
    platform: state
    to: 'on'
  condition: []
  action:
    - entity_id: switch.hallway_relay_1
      service: switch.turn_on
    - entity_id: light.hall_white
      service: light.turn_on
      data:
        transition: 0
        brightness_pct: 100
    - entity_id: light.hall_colour
      service: light.turn_off
- alias: Hall Switch2
  trigger:
  - entity_id: binary_sensor.hallway_switch2
    platform: state
    to: 'on'
  condition: []
  action:
    - entity_id: switch.hallway_relay_1
      service: switch.turn_on
    - entity_id: light.hall_white
      service: light.turn_off
    - entity_id: light.hall_colour
      service: light.turn_on
      data:
        transition: 0
        color_name: blue
        brightness_pct: 50
- alias: Hall Switch3
  trigger:
  - entity_id: binary_sensor.hallway_switch3
    platform: state
    to: 'on'
  condition: []
  action:
    - entity_id: light.hall_white
      service: light.turn_off
    - entity_id: light.hall_colour
      service: light.turn_off
# Change the hall light colour based on time and if the kids lights are on
- id: hall_nightlight
  alias: Hall nightlight
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.hall_colour
      transition: 0
  - service: light.turn_on
    data:
      entity_id: light.hall_white
      transition: 0
      brightness_pct: 50
- id: hall_morning
  alias: Hall morning
  trigger:
    platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.hall_colour
  - service: light.turn_off
    data:
      entity_id: light.hall_white
- id: hall_kidslightson
  alias: Hall Kids lights on
  trigger:
    - platform: state
      entity_id: light.xander_bedroom_light
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.xander_bedroom_light
        state: 'on'
      - condition: time
        after: '19:00:00'
        before: '06:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hall_colour
        transition: 0
    - service: light.turn_on
      data:
        entity_id: light.hall_white
        transition: 0
        brightness_pct: 50
- id: hall_kidslightsoff
  alias: Hall Kids lights off
  trigger:
    - platform: state
      entity_id: light.xander_bedroom_light
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.xander_bedroom_light
        state: 'off'
      - condition: time
        after: '19:00:00'
        before: '06:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_colour
        transition: 0
        color_name: blue
        brightness_pct: 50
    - service: light.turn_off
      data:
        entity_id: light.hall_white
        transition: 0
