- alias: Dimmer - Hall
  trigger:
  - entity_id: sensor.hall_dimmer_action
    platform: state
  condition: []
  action:
    - entity_id: light.hall_white
      service_template: >
        {% if trigger.to_state.state|length %}light.turn_on
        {% else %}script.noop
        {% endif %}
      data_template:
        transition: 0
        brightness_pct: >
          {% if trigger.to_state.state == 'on-press' %}100
          {% elif trigger.to_state.state == 'up-press' %}50
          {% else %}0
          {% endif %}
    - entity_id: light.hall_colour
      service_template: >
        {% if trigger.to_state.state|length %}light.turn_on
        {% else %}script.noop
        {% endif %}
      data_template:
        transition: 0
        brightness_pct: >
          {% if trigger.to_state.state == 'down-press' %}100
          {% else %}0
          {% endif %}
# Change the hall light colour based on time and if the kids lights are on
- id: hall_nightlight
  alias: Hall nightlight
  trigger:
    platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.hall_colour
      transition: 0
  - service: light.turn_on
    data:
      entity_id: light.hall_white
      transition: 0
      brightness_pct: 50
- id: hall_morning
  alias: Hall morning
  trigger:
    platform: time
    at: '06:30:00'
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.hall_colour
  - service: light.turn_off
    data:
      entity_id: light.hall_white
- id: hall_kidslightson
  alias: Hall Kids lights on
  trigger:
    - platform: state
      entity_id: group.xander_bedroom_lights
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.xander_bedroom_lights
        state: 'on'
      - condition: time
        after: '19:00:00'
        before: '06:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.hall_colour
        transition: 0
    - service: light.turn_on
      data:
        entity_id: light.hall_white
        transition: 0
        brightness_pct: 50
- id: hall_kidslightsoff
  alias: Hall Kids lights off
  trigger:
    - platform: state
      entity_id: group.xander_bedroom_lights
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.xander_bedroom_lights
        state: 'off'
      - condition: time
        after: '19:00:00'
        before: '06:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hall_colour
        transition: 0
        color_name: blue
        brightness_pct: 50
    - service: light.turn_off
      data:
        entity_id: light.hall_white
        transition: 0
      
