- alias: All off each night - HOLIDAYS
  trigger:
    platform: time
    at: '21:30:00'
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
- alias: All off each morn - HOLIDAYS
  trigger:
    platform: time
    at: '10:31:00'
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
- alias: All off each day - HOLIDAYS
  trigger:
    platform: time
    at: '16:31:00'
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
