- alias: Holidays - All off each night
  trigger:
    platform: time
    at: '21:30:00'
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
- alias: Holidays - All off each morning
  trigger:
    platform: time
    at: '10:31:00'
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
- alias: Holidays - All off each day
  trigger:
    platform: time
    at: '16:31:00'
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.all_off
