- alias: Kitchen - Switch1
  trigger:
  - entity_id: binary_sensor.kitchen_switch1
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.kitchen_relay_1
    service: switch.turn_on
  - entity_id: light.kitchen_light_group
    service: light.turn_on
    data:
      transition: 1
      brightness_pct: 100
- alias: Kitchen - Switch2
  trigger:
  - entity_id: binary_sensor.kitchen_switch2
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.kitchen_relay_1
    service: switch.turn_on
  - entity_id: light.kitchen_light_group
    service: light.turn_on
    data:
      transition: 1
      brightness_pct: 10
- alias: Kitchen - Switch3
  trigger:
  - entity_id: binary_sensor.kitchen_switch3
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: light.kitchen_light_group
    service: light.turn_off
    data:
      transition: 1
