- alias: Dimmer - Kitchen
  trigger:
  - entity_id: sensor.kitchen_dimmer_action
    platform: state
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state in ['on-press', 'up-press', 'down-press', 'off-press'] }}"
  action:
  - entity_id: light.kitchen_light_group
    service_template: light.turn_on
    data_template:
      brightness_pct: >
        {% if trigger.to_state.state == 'on-press' %} 100
        {% elif trigger.to_state.state == 'up-press' %} 50
        {% elif trigger.to_state.state == 'down-press' %} 50
        {% elif trigger.to_state.state == 'off-press' %} 0
        {% endif %}
      color_name: >
        {% if trigger.to_state.state == 'down-press' %} blue
        {% else %} white
        {% endif %}
