- alias: Kitchen light on
  trigger:
  - entity_id: sensor.kitchen_dimmer_action
    platform: state
    to: 'on-press'
  condition: []
  action:
  - entity_id: group.kitchen_lights
    service: light.turn_on
    data:
      brightness_pct: 100
- alias: Kitchen light up press
  trigger:
  - entity_id: sensor.kitchen_dimmer_action
    platform: state
    to: 'up-press'
  condition: []
  action:
  - entity_id: group.kitchen_lights
    service: light.turn_on
    data:
       brightness_pct: 50
- alias: Kitchen light down press
  trigger:
  - entity_id: sensor.kitchen_dimmer_action
    platform: state
    to: 'down-press'
  condition: []
  action:
  - entity_id: group.kitchen_lights
    service: light.turn_on
    data:
      brightness_pct: 10
- alias: Kitchen light off
  trigger:
  - entity_id: sensor.kitchen_dimmer_action
    platform: state
    to: 'off-press'
  condition: []
  action:
  - entity_id: group.kitchen_lights
    service: light.turn_off
