- alias: Day
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      effect: Slow Random Effect
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on
- alias: Night
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      effect: Rainbow
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on
- alias: Living Room Click 4
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 4_click_up
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.turn_off
- alias: Living Room Click 3
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 3_click_up
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.night_mode
- alias: Living Room Click 1
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 1_click_up
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.normal
- alias: Living Room Click 2
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 2_click_up
  condition: []
  action:
  - service: scene.turn_on
    data:
      entity_id: scene.movies
