- id: day
  alias: Time - Day
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      effect: Slow Random Effect
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on
- id: night
  alias: Time - Night
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      effect: Rainbow
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on

- alias: Living Room Preset selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
  action:
    service_template: >
      {% if trigger.to_state.state|length %}scene.turn_on
      {% else %}script.noop
      {% endif %}
    data_template:
      entity_id: >
        {% if trigger.to_state.state == "Normal" %}scene.normal
        {% elif trigger.to_state.state == "Movie" %}scene.movies
        {% elif trigger.to_state.state == "Night" %}scene.night
        {% elif trigger.to_state.state == "TurnOff" %}scene.turn_off
        {% endif %}
- alias: Dimmer - Living room
  trigger:
  - entity_id: sensor.livingroom_dimmer_action
    platform: state
  condition: []
  action:
    - entity_id: input_select.livingroom_preset
      service_template: >
        {% if trigger.to_state.state|length %}input_select.select_option
        {% else %}script.noop
        {% endif %}
      data_template:
        option: >
          {% if trigger.to_state.state == "on-press" %}Normal
          {% elif trigger.to_state.state == "up-press" %}Movie
          {% elif trigger.to_state.state == "down-press" %}Night
          {% elif trigger.to_state.state == "off-press" %}TurnOff
          {% endif %}
