- id: day
  alias: Day
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      effect: Slow Random Effect
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on
- id: night
  alias: Night
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      effect: Rainbow
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on

- id: living_room_click_1
  alias: Living Room Click 1
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 1_click_up
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "Normal"
- id: living_room_click_2
  alias: Living Room Click 2
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 2_click_up
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "Movie"
- id: living_room_click_3
  alias: Living Room Click 3
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 3_click_up
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "Night"
- id: living_room_click_4
  alias: Living Room Click 4
  trigger:
  - entity_id: sensor.living_room_switch
    platform: state
    to: 4_click_up
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "TurnOff"

- alias: Living Room Normal selected
  id: living_room_normal_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "Normal"
  action:
    service: scene.turn_on
    entity_id: scene.normal
- alias: Living Room Movie selected
  id: living_room_movie_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "Movie"
  action:
    service: scene.turn_on
    entity_id: scene.movies
- alias: Living Room Night selected
  id: living_room_night_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "Night"
  action:
    service: scene.turn_on
    entity_id: scene.night
- alias: Living Room Turn Off selected
  id: living_room_turnoff_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "TurnOff"
  action:
    service: scene.turn_on
    entity_id: scene.turn_off
