- id: day
  alias: Time - Day
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      effect: Slow Random Effect
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on
- id: night
  alias: Time - Night
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      effect: Rainbow
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on

- alias: Living Room Normal selected
  id: living_room_normal_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "Normal"
  action:
    service: scene.turn_on
    entity_id: scene.normal
- alias: Living Room Movie selected
  id: living_room_movie_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "Movie"
  action:
    service: scene.turn_on
    entity_id: scene.movies
- alias: Living Room Night selected
  id: living_room_night_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "Night"
  action:
    service: scene.turn_on
    entity_id: scene.night
- alias: Living Room Turn Off selected
  id: living_room_turnoff_selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
    to: "TurnOff"
  action:
    service: scene.turn_on
    entity_id: scene.turn_off
- alias: Living room on
  trigger:
  - entity_id: sensor.hueswitch_1_action
    platform: state
    to: 'on-press'
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "Normal"
- alias: Living room up
  trigger:
  - entity_id: sensor.hueswitch_1_action
    platform: state
    to: 'up-press'
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "Movie"
- alias: Living room down
  trigger:
  - entity_id: sensor.hueswitch_1_action
    platform: state
    to: 'down-press'
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "Night"
- alias: Living room off
  trigger:
  - entity_id: sensor.hueswitch_1_action
    platform: state
    to: 'off-press'
  condition: []
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.livingroom_preset
      option: "TurnOff"
