- id: day
  alias: Time - Day
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - data:
      effect: Slow Random Effect
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on
- id: night
  alias: Time - Night
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      effect: Rainbow
      entity_id: light.family_room_strip
    entity_id: light.family_room_strip
    service: light.turn_on

- alias: Living Room Preset selected
  trigger:
    platform: state
    entity_id: input_select.livingroom_preset
  action:
    service_template: >
      {% if trigger.to_state.state|length %}scene.turn_on
      {% else %}script.noop
      {% endif %}
    data_template:
      entity_id: >
        {% if trigger.to_state.state == "Normal" %}scene.normal
        {% elif trigger.to_state.state == "Movie" %}scene.movies
        {% elif trigger.to_state.state == "Night" %}scene.night
        {% elif trigger.to_state.state == "TurnOff" %}scene.turn_off
        {% endif %}
- alias: Dimmer - Living room
  trigger:
  - entity_id: sensor.livingroom_dimmer_action
    platform: state
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state in ['on-press', 'up-press', 'down-press', 'off-press'] }}"
  action:
    - entity_id: input_select.livingroom_preset
      service: input_select.select_option
      data_template:
        option: >
          {% if trigger.to_state.state == "on-press" %}Normal
          {% elif trigger.to_state.state == "up-press" %}Movie
          {% elif trigger.to_state.state == "down-press" %}Night
          {% elif trigger.to_state.state == "off-press" %}TurnOff
          {% endif %}
- alias: Living Room Preset manual off
  trigger:
    - entity_id: light.livingroom_light_group
      platform: state
      to: "off"
      for: "00:00:05"
  condition:
    - condition: template
      value_template: '{{ not is_state("input_select.livingroom_preset", "TurnOff") }}'
  action:
    - entity_id: input_select.livingroom_preset
      service: input_select.select_option
      data:
        option: "TurnOff"
- alias: Living Room Preset manual on
  trigger:
    - entity_id: light.livingroom_light_group
      platform: state
      to: "on"
      for: "00:00:05"
  condition:
    - condition: template
      value_template: '{{ is_state("input_select.livingroom_preset", "TurnOff") }}'
  action:
    - entity_id: input_select.livingroom_preset
      service: input_select.select_option
      data:
        option: "Normal"
