- alias: Dimmer - Lucas
  trigger:
  - entity_id: sensor.lucas_bedroom_dimmer_action
    platform: state
  condition:
    - condition: template
      value_template: "{{ trigger.to_state.state in ['on-press', 'up-press', 'down-press', 'off-press'] }}"
  action:
  - entity_id: light.lucas_bedroom_light
    service: light.turn_on
    data_template:
      brightness_pct: >
        {% if trigger.to_state.state == 'on-press' %} 100
        {% elif trigger.to_state.state == 'up-press' %} 50
        {% elif trigger.to_state.state == 'down-press' %} 1
        {% elif trigger.to_state.state == 'off-press' %} 0
        {% endif %}
