- alias: Lucas switch1
  trigger:
  - entity_id: binary_sensor.zemi2_switch1_2
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: light.lucas_bedroom_light
    service: light.turn_on
    data_template:
      brightness: >
        {% if state_attr('light.lucas_bedroom_light','brightness') | float > 100 %}0
        {% else %}255
        {% endif %}
- alias: Lucas switch2
  trigger:
  - entity_id: binary_sensor.zemi2_switch2_2
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: light.lucas_bedroom_light
    service: light.turn_on
    data_template:
      brightness: >
        {% if state_attr('light.lucas_bedroom_light','brightness') | float == 40 %}0
        {% else %}40
        {% endif %}