- alias: Lucas switch1
  trigger:
  - entity_id: binary_sensor.lucas_switch1
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: light.lucas_bedroom_light
    service: light.turn_on
    data_template:
      brightness: >
        {% if state_attr('light.lucas_bedroom_light','brightness') | float > 100 %}0
        {% else %}255
        {% endif %}
  - entity_id: switch.lucas_relay_1
    service: switch.turn_on
- alias: Lucas switch2
  trigger:
  - entity_id: binary_sensor.lucas_switch2
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: light.lucas_bedroom_light
    service: light.turn_on
    data_template:
      brightness: >
        {% if state_attr('light.lucas_bedroom_light','brightness') | float == 40 %}0
        {% else %}40
        {% endif %}