- alias: Lucas switch1
  trigger:
  - entity_id: binary_sensor.lucas_switch1
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: light.lucas
    service: light.turn_on
    data:
      brightness_pct: 1
      white_value: 255
  - entity_id: switch.lucas_relay_1
    service: switch.turn_on
- alias: Lucas switch2
  trigger:
  - entity_id: binary_sensor.lucas_switch2
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: switch.lucas_relay_1
    service: switch.turn_on
  - entity_id: light.lucas
    service: light.turn_on
    data:
      white_value: 120
      brightness_pct: 1
- alias: Lucas switch3
  trigger:
  - entity_id: binary_sensor.lucas_switch3
    platform: state
    to: "on"
  condition: []
  action:
  - entity_id: light.lucas
    service: light.turn_off