- alias: Office light on
  id: office_light_on
  trigger:
  - entity_id: light.office_light
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.office_speaker
    service: switch.turn_on
- alias: Office light off
  id: office_light_off
  trigger:
  - entity_id: light.office_light
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: switch.office_speaker
    service: switch.turn_off
