- alias: 'People not home'
  trigger:
    - platform: state
      entity_id: person.mel
      from: 'home'
    - platform: state
      entity_id: person.chris
      from: 'home'
  condition:
    condition: template
    value_template: "{% if not (is_state('person.chris', 'home') or is_state('person.mel', 'home')) %} true {% else %} false {% endif %}"
  action:
    - service: switch.toggle
      entity_id: switch.backroom_ptz_away
    - service: notify.telegram_notify
      data:
        message: "Feeling lonely"
    - service: notify.hangout_notify
      data:
        message: "Feeling lonely"
- alias: 'Mel home'
  trigger:
    - platform: state
      entity_id: person.mel
      to: 'home'
  condition: []
  action:
    - service: switch.toggle
      entity_id: switch.backroom_ptz_home
    - service: notify.telegram_notify
      data:
        message: "Yay - Mel's home"
    - service: notify.hangout_notify
      data:
        message: "Yay - Mel's home"
- alias: 'People home'
  trigger:
    - platform: state
      entity_id: person.chris
      to: 'home'
  condition: []
  action:
    - service: switch.toggle
      entity_id: switch.backroom_ptz_home
    - service: notify.telegram_notify
      data:
        message: "Yay - you're home"
    - service: notify.hangout_notify
      data:
        message: "Yay - you're home"
