- alias: 'Startup - set theme'
  id: startup_actions
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: frontend.set_theme
      data:
        name: "blue_night"
    - service: mqtt.publish
      data:
        topic: "sonoffs/cmnd/state"
        payload: ""
