- alias: 'Startup - set theme'
  id: startup_actions
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: day
