- alias: Xander light on
  trigger:
  - entity_id: sensor.xander_dimmer_action
    platform: state
    to: 'on-press'
  condition: []
  action:
  - entity_id: group.xander_bedroom_lights
    service: light.turn_on
    data:
      brightness_pct: 100
- alias: Xander light up press
  trigger:
  - entity_id: sensor.xander_dimmer_action
    platform: state
    to: 'up-press'
  condition: []
  action:
  - entity_id: group.xander_bedroom_lights
    service: light.turn_on
    data:
       brightness_pct: 50
- alias: Xander light down press
  trigger:
  - entity_id: sensor.xander_dimmer_action
    platform: state
    to: 'down-press'
  condition: []
  action:
  - entity_id: group.xander_bedroom_lights
    service: light.turn_on
    data:
      brightness_pct: 10
- alias: Xander light off
  trigger:
  - entity_id: sensor.xander_dimmer_action
    platform: state
    to: 'off-press'
  condition: []
  action:
  - entity_id: group.xander_bedroom_lights
    service: light.turn_off
