substitutions:
  name: backyardcam

<<: !include common/esp8266.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Backyard cam Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Backyard Cam"
    pin: GPIO12
    id: relay
    inverted: no

status_led:
  pin:
    number: GPIO13
    inverted: yes

