substitutions:
  name: backroom
  
<<: !include common/esp8266.yaml

switch:
  - platform: gpio
    name: "Backroom relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Backroom relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Backroom relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Backroom blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Backroom Switch1"
    on_press:
      then:
        - mqtt.publish:
            topic: Backroom_Middle/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
        - mqtt.publish:
            topic: Backroom_Right/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
        - mqtt.publish:
            topic: Backroom_Left/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Backroom Switch2"
    on_press:
      switch.toggle: relay1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Backroom Switch3"
    on_press:
      then:
        - switch.turn_off: relay1
        - mqtt.publish:
            topic: Backroom_Left/cmnd/POWER
            payload: "OFF"
        - mqtt.publish:
            topic: Backroom_Middle/cmnd/POWER
            payload: "OFF"
        - mqtt.publish:
            topic: Backroom_Right/cmnd/POWER
            payload: "OFF"
