esphome:
  name: bedroomesp
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO13
    num_leds: 1
    rgb_order: RGB
    name: "Bedroom LED"

i2c:

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "Bedroom Temperature"
      oversampling: 16x
    pressure:
      name: "Bedroom Pressure"
      unit_of_measurement: mbar
    address: 0x76
    update_interval: 60s
