substitutions:
  device: bedroom
  
<<: !include common/common.yaml

switch:
  - platform: gpio
    name: "Bedroom relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Bedroom relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Bedroom relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Bedroom blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Bedroom Switch1"
    on_press:
      then:
        - switch.turn_on: relay1
        - switch.turn_on: relay2
        - mqtt.publish:
            topic: BedroomA/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
        - mqtt.publish:
            topic: BedroomB/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Bedroom Switch2"
    on_press:
      then:
        - switch.turn_on: relay1
        - switch.turn_on: relay2
        - mqtt.publish:
            topic: BedroomA/cmnd/Backlog
            payload: "CT 370; Dimmer 50; POWER ON"
        - mqtt.publish:
            topic: BedroomB/cmnd/Backlog
            payload: "CT 370; Dimmer 50; POWER ON"
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Bedroom Switch3"
    on_press:
      then:
        - mqtt.publish:
            topic: BedroomA/cmnd/POWER
            payload: "OFF"
        - mqtt.publish:
            topic: BedroomB/cmnd/POWER
            payload: "OFF"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
        - switch.turn_off: relay2
