esphome:
  name: bulb_kitchen_back
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

web_server:
  port: 80

output:
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO12
 
# Define a light entity
light:
  - platform: monochromatic
    name: Kitchen Back
    output: output_white
    
    restore_mode: ALWAYS_ON