esphome:
  name: bulb2
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

output:
  - platform: esp8266_pwm
    id: IO1
    pin: GPIO5
  
light:
  - platform: fastled_spi
    chipset: SM16716
    data_pin: GPIO14
    clock_pin: GPIO04
    num_leds: 8
    name: "Bulb Colour"
  - platform: monochromatic
    name: "Bulb White"
    output: IO1
    
