esphome:
  name: bulb3
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

output:
  - platform: esp8266_pwm
    id: IO1
    pin: GPIO5
  
light:
  - platform: fastled_spi
    chipset: SM16716
    data_pin: GPIO14
    clock_pin: GPIO04
    num_leds: 8
    name: "Bulb Colour"
    effects:
      - addressable_rainbow:
      - addressable_random_twinkle:
      - addressable_color_wipe:
          name: Police Lights
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 4
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 4
          add_led_interval: 100ms
  - platform: monochromatic
    name: "Bulb White"
    output: IO1
    
