esphome:
  name: bulb_entry
  platform: ESP8266
  board: esp01_1m


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:

ota:

sm16716:
  data_pin: GPIO14
  clock_pin: GPIO4
  num_channels: 3
  num_chips: 1
    
output:
  - platform: sm16716
    id: output_red
    channel: 0
  - platform: sm16716
    id: output_green
    channel: 1
  - platform: sm16716
    id: output_blue
    channel: 2
  - platform: esp8266_pwm
    id: IO1
    pin: GPIO5
  
light:
  - platform: rgbw
    name: "Entry"
    red: output_red
    green: output_green
    blue: output_blue
    white: IO1
