esphome:
  name: entry
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Entry relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Entry relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Entry blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Entry Switch1"
    on_click:
      then:
        - switch.turn_on: relay1
        - switch.turn_on: relay2
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Entry Switch2"
    on_click:
      then:
        - switch.turn_on: relay1
        - switch.turn_on: relay2