substitutions:
  device: entry
  
<<: !include common/common.yaml

switch:
  - platform: gpio
    name: "Entry relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Entry relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Entry blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Entry Switch1"
    on_press:
      then:
        - switch.turn_on: relay2
        - mqtt.publish:
            topic: Entry/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER toggle"
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Entry Switch2"
    on_press:
      switch.toggle: relay1