esphome:
  name: esp32
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: malware-24
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "PIR Sensor"
    device_class: motion
    