esphome:
  name: frontdoor
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "malware-24"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
web_server:
ota:

binary_sensor:
  - platform: gpio
    pin:
      number: 15
      mode: INPUT_PULLDOWN
      inverted: True
    name: "door"
    device_class: door

