esphome:
  name: hallway
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

mqtt:
  broker: 192.168.86.2
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

ota:

switch:
  - platform: gpio
    name: "Hallway relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Hallway relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Hallway relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Hallway blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Hallway Switch1"
    on_press:
      then:
        - switch.turn_on: relay1
        - mqtt.publish:
            topic: Hallbulb/cmnd/Backlog
            payload: "White 100; Dimmer 100; POWER ON"
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Hallway Switch2"
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Hallway Switch3"
    on_press:
      then:
        - mqtt.publish:
            topic: Hallbulb/cmnd/POWER
            payload: "OFF"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
