esphome:
  name: kitchen
  platform: ESP8266
  board: esp01_1m
wifi:
  ssid: virus
  password: ithankthegoodness

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Kitchen relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Kitchen relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Kitchen relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Kitchen blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Kitchen Switch1"
    on_click:
      switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Kitchen Switch2"
    on_click:
      switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Kitchen Switch3"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
