esphome:
  name: kitchen
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

mqtt:
  broker: 192.168.86.2
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false

ota:

switch:
  - platform: gpio
    name: "Kitchen relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Kitchen relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Kitchen relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Kitchen blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Kitchen Switch1"
    on_press:
      then:
        - switch.turn_on: relay1
        - switch.turn_on: relay2
        - mqtt.publish:
            topic: Kitchen_Back/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
        - mqtt.publish:
            topic: Kitchen_Front/cmnd/Backlog
            payload: "CT 370; Dimmer 100; POWER ON"
        - mqtt.publish:
            topic: "zigbee2mqtt/Kitchen Counter/set"
            payload: '{"state": "on", "brightness": "255", "color_temp": "350"}'
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Kitchen Switch2"
    on_press:
      then:
        - switch.turn_on: relay1
        - switch.turn_on: relay2
#        - mqtt.publish:
#            topic: Kitchen_Front/cmnd/Backlog
#            payload: "CT 370; Dimmer 40; POWER ON"
#        - mqtt.publish:
#            topic: Kitchen_Back/cmnd/Backlog
#            payload: "CT 370; Dimmer 40; POWER ON"
#        - mqtt.publish:
#            topic: "zigbee2mqtt/Kitchen Counter/set"
#            payload: '{"state": "on", "brightness": "90", "color_temp": "420"}'
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Kitchen Switch3"
    on_press:
      then:
        - mqtt.publish:
            topic: Kitchen_Back/cmnd/POWER
            payload: "OFF"
        - mqtt.publish:
            topic: Kitchen_Front/cmnd/POWER
            payload: "OFF"
        - mqtt.publish:
            topic: "zigbee2mqtt/Kitchen Counter/set"
            payload: '{"state": "off"}'
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
        - switch.turn_off: relay2
