substitutions:
  name: laundrytoilet

<<: !include common/esp8266.yaml

switch:
  - platform: gpio
    name: "Laundry Toilet Light"
    pin: GPIO12
    id: relay1
  - platform: gpio
    name: "Laundry Toilet blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "Laundry Toilet Switch"
    on_press:
      then:
        switch.toggle: relay1
