substitutions:
  device: laundry
  board: esp01_1m

<<: !include common/common.yaml

switch:
  - platform: gpio
    name: "Laundry Light"
    pin: GPIO12
    id: relay1
  - platform: gpio
    name: "Laundry blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "Laundry Switch"
    on_press:
      then:
        switch.toggle: relay1
