substitutions:
  name: lightstrip

<<: !include common/d1mini.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 52
    rgb_order: GRB
    name: "TV backlight"
    effects:
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
