esphome:
  name: lightstrip3
  platform: ESP8266
  board: d1_mini


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 52
    rgb_order: GRB
    name: "Office Strip"
    id: strip1
    effects:
      # Customize parameters
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
