esphome:
  name: lightstrip2
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 50
    then:
     - light.turn_on:
         id: strip1
         brightness: 100%
         red: 100%
         green: 50%
         blue: 1%
     - delay: 1s
     - light.turn_on:
         id: strip1
         effect: "Random Twinkle"

wifi:
  ssid: "office"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 52
    rgb_order: GRB
    name: "Family Room Strip"
    id: strip1
    effects:
      # Customize parameters
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
