substitutions:
  name: lightstrip2
  
<<: !include common/d1mini.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D1
    num_leds: 52
    rgb_order: GRB
    name: "Family Room Strip"
    id: strip1
    effects:
      # Customize parameters
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
