esphome:
  name: livingroom
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Livingroom relay 1"
    pin: GPIO13
    id: relay1
    interlock: [relay2, relay3]
  - platform: gpio
    name: "Livingroom relay 2"
    pin: GPIO12
    id: relay2
    interlock: [relay1, relay3]
  - platform: gpio
    name: "Livingroom relay 3"
    pin: GPIO14
    id: relay3
    interlock: [relay2, relay1]
  - platform: gpio
    name: "Livingroom blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Livingroom Switch1"
    on_click:
      switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Livingroom Switch2"
    on_click:
      switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Livingroom Switch3"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
