substitutions:
  name: livingroom

<<: !include common/esp8266.yaml

switch:
  - platform: gpio
    name: "Livingroom relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Livingroom relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Livingroom relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Livingroom blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Livingroom Switch1"
    on_press:
      switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Livingroom Switch2"
    on_press:
      switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Livingroom Switch3"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
