substitutions:
  name: lucas
  
<<: !include common/esp8266.yaml

switch:
  - platform: gpio
    name: "Lucas relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Lucas relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Lucas relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Lucas blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Lucas Switch1"
    on_press:
      then:
        - switch.turn_on: relay1
        - mqtt.publish:
            topic: Lucas/cmnd/Backlog
            payload: "Scheme 0; CT 370; Dimmer 100; POWER ON"
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Lucas Switch2"
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at most 0.3s
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - logger.log: "Double-Clicked"
          - switch.turn_on: relay1
          - mqtt.publish:
              topic: Lucas/cmnd/Backlog
              payload: "Color1 2;Scheme 2; Dimmer 100; POWER ON"
      - timing:
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - logger.log: "Single-Clicked"
          - switch.turn_on: relay1
          - mqtt.publish:
              topic: Lucas/cmnd/Backlog
              payload: "Scheme 0; White 100; CT 370; Dimmer 50; POWER ON"
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Lucas Switch3"
    on_press:
      then:
        - mqtt.publish:
            topic: Lucas/cmnd/POWER
            payload: "OFF"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
