substitutions:
  device: officestrip
  board: d1_mini

<<: !include common/common.yaml

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 95
    rgb_order: GRB
    name: "Office Shelf"
    effects:
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
      - addressable_color_wipe:
      - strobe:
      - strobe:
          name: Fast Strobe
          colors:
            - state: True
              duration: 25ms
            - state: False
              duration: 25ms
      - addressable_flicker:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 50%
              green: 0%
              blue: 0%
              num_leds: 2
            - red: 0%
              green: 0%
              blue: 50%
              num_leds: 2
          add_led_interval: 100ms
          reverse: False