esphome:
  name: officespeaker
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: virus
  password: !secret wifi_password

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Office Speaker Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Office Speaker"
    pin: GPIO12
    id: relay
    inverted: no

status_led:
  pin:
    number: GPIO13
    inverted: yes

