esphome:
  name: officeesp
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "Office Temperature"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
      unit_of_measurement: mbar
    address: 0x76
    update_interval: 60s
