substitutions:
  device: office
  
<<: !include common/common.yaml

switch:
  - platform: gpio
    name: "Office relay 1"
    pin: GPIO13
    id: relay1
  - platform: gpio
    name: "Office relay 2"
    pin: GPIO12
    id: relay2
  - platform: gpio
    name: "Office relay 3"
    pin: GPIO14
    id: relay3
  - platform: gpio
    name: "Office blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "Office Switch1"
    on_press:
      then:
        - switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO5
      inverted: True
    name: "Office Switch2"
    on_press:
      then:
        - switch.turn_on: relay1
  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    name: "Office Switch3"
    on_click:
      min_length: 2000ms
      max_length: 5000ms
      then:
        - switch.turn_off: relay1
