substitutions:
  device: officeesp
  board: d1_mini
  
<<: !include common/common.yaml

web_server:
  port: 80
  
i2c:

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "Office Temperature"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
      unit_of_measurement: mbar
    address: 0x76
    update_interval: 60s


light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 35
    rgb_order: GRB
    name: "Office Strip"
    id: strip1
    effects:
      # Customize parameters
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
