esphome:
  name: officeesp
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "malware-24"
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  scan: True

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "Office Temperature"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
      unit_of_measurement: mbar
    address: 0x76
    update_interval: 60s
