esphome:
  name: officespeaker
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

web_server:
  css_url: https://home.adebenham.com:8123/local/esphome/webserver-v1.min.css
  js_url: https://home.adebenham.com:8123/local/esphome/webserver-v1.min.css

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Office Speaker Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Office Speaker"
    pin: GPIO12
    id: relay
    inverted: no

status_led:
  pin:
    number: GPIO13
    inverted: yes

