substitutions:
  name: officeesp
  
<<: !include common/d1mini.yaml

i2c:

# Example configuration entry
sensor:
  - platform: bmp280
    temperature:
      name: "Office Temperature"
      oversampling: 16x
    pressure:
      name: "Office Pressure"
      unit_of_measurement: mbar
    address: 0x76
    update_interval: 60s


light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D4
    num_leds: 35
    rgb_order: GRB
    name: "Office Strip"
    id: strip1
    effects:
      # Customize parameters
      - random:
          name: "Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - random:
          name: "Fast Random Effect"
          transition_length: 4s
          update_interval: 5s
      - addressable_rainbow:
      - addressable_random_twinkle:
      - addressable_color_wipe:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 1
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: False
