esphome:
  name: powerboard
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

switch:
  - platform: gpio
    name: "Powerboard Outlet 1"
    pin: GPIO05
    id: relay1
  - platform: gpio
    name: "Powerboard Outlet 2"
    pin: GPIO04
    id: relay2
  - platform: gpio
    name: "Powerboard Outlet 3"
    pin: GPIO13
    id: relay3
  - platform: gpio
    name: "Powerboard Outlet 4"
    pin: GPIO12
    id: relay4
    