substitutions:
  name: powerboard
  
<<: !include common/esp8266.yaml

switch:
  - platform: gpio
    name: "Powerboard Outlet 1"
    pin: GPIO05
    id: relay1
  - platform: gpio
    name: "Powerboard Outlet 2"
    pin: GPIO04
    id: relay2
  - platform: gpio
    name: "Powerboard Outlet 3"
    pin: GPIO13
    id: relay3
  - platform: gpio
    name: "Powerboard Outlet 4"
    pin: GPIO12
    id: relay4
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: "Powerboard Button"
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - switch.toggle: relay1
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - switch.toggle: relay2
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - switch.toggle: relay3
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
        - switch.toggle: relay4
