substitutions:
  device: powerboard
  board: esp01_1m
  
<<: !include common/common.yaml

web_server:
  port: 80

switch:
  - platform: gpio
    name: "Powerboard Outlet 1"
    pin: GPIO05
    id: relay1
  - platform: gpio
    name: "Powerboard Outlet 2"
    pin: GPIO04
    id: relay2
  - platform: gpio
    name: "Powerboard Outlet 3"
    pin: GPIO13
    id: relay3
  - platform: gpio
    name: "Powerboard Outlet 4"
    pin: GPIO12
    id: relay4
    