esphome:
  name: powermeter
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

sensor:
  - platform: pzemac
    current:
      name: "House Current"
    voltage:
      name: "House Voltage"
    power:
      name: "House Power"
    frequency:
      name: "House Frequency"
    power_factor:
      name: "House Power Factor"
    update_interval: 60s
    address: 1
