esphome:
  name: sensorlight
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sensorlight Button"
    on_press:
      - light.toggle: light
    
light:
  - platform: binary
    name: "Sensor Light"
    id: light
    output: relay
    
output:
  - platform: gpio
    pin: GPIO12
    id: relay
    inverted: no

status_led:
  pin:
    number: GPIO13
    inverted: yes
