esphome:
  name: sonoff2
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: malware-24
  password: !secret wifi_password

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff2 Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff2 Relay"
    pin: GPIO12
    id: relay
    inverted: no

status_led:
  pin:
    number: GPIO13
    inverted: yes
