substitutions:
  device: toilet
  board: esp01_1m
  
<<: !include common/common.yaml

switch:
  - platform: gpio
    name: "Toilet Light"
    pin: GPIO12
    id: relay1
  - platform: gpio
    name: "Toilet blue LED"
    pin: GPIO2
    inverted: True
    id: blueLED
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    name: "Toilet Switch"
    on_click:
      min_length: 50ms
      max_length: 5000ms
      then:
        switch.toggle: relay1