esphome:
  name: tvpower
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "TV Power Button"
    on_press:
      - switch.toggle: relay
  - platform: template
    name: "TV Active"
    lambda: |-
      if (id(power).state > 100 ) {
        return true;
      } else {
        return false;
      }
      
switch:
  - platform: gpio
    name: "TV Power"
    pin: GPIO14
    id: relay
    inverted: no

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: hlw8012
    sel_pin: GPIO12
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current:
      name: "TV Power Current"
    voltage:
      name: "TV Power Voltage"
    power:
      name: "TV Power Watts"
      id: power
    update_interval: 60s