substitutions:
  name: washing

<<: !include common/esp8266.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Washing Button"
    on_press:
      - switch.toggle: relay
  - platform: template
    name: "Washing Active"
    lambda: |-
      if (id(power).state > 100 ) {
        return true;
      } else {
        return false;
      }

switch:
  - platform: gpio
    name: "Washing"
    pin: GPIO14
    id: relay
    inverted: no
    icon: mdi:washing-machine
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: yes
    
sensor:
  - platform: hlw8012
    sel_pin: GPIO12
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current:
      name: "Washing Current"
      unit_of_measurement: A
    voltage:
      name: "Washing Voltage"
      unit_of_measurement: V
    power:
      name: "Washing Watts"
      id: power
      unit_of_measurement: W
    change_mode_every: 8
    current_resistor: 0.00087
    voltage_divider: 2030
    update_interval: 5s
