light:
  - platform: group
    name: Backroom Lights
    #icon: mdi:castle
    entities:
      - light.backroom_middle
      - light.backroom_right
      - light.backroom_left

camera:
  - platform: generic
    name: backroom
    still_image_url: http://192.168.86.2:6080/zm/cgi-bin/zms?mode=single&monitor=1
    stream_source: rtsp://admin:542285@192.168.86.42/live/profile.0

switch:
  - platform: template
    switches:
      backroom_lights:
        icon_template: mdi:castle
        friendly_name: "Backroom"
        value_template: "{{ states('light.backroom_lights') }}"
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.backroom_lights
            brightness_pct: 100
            color_temp: 370
            white_value: 255
            transition: 1
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.backroom_lights
            transition: 1

automation:
  - id: day
    alias: Backroom - Time - Day
    trigger:
    - event: sunrise
      platform: sun
    condition: []
    action:
    - data:
        effect: Slow Random Effect
        entity_id: light.family_room_strip
      entity_id: light.family_room_strip
      service: light.turn_on
  - id: night
    alias: Backroom - Time - Night
    trigger:
    - event: sunset
      platform: sun
    condition: []
    action:
    - data:
        effect: Rainbow
        entity_id: light.family_room_strip
      entity_id: light.family_room_strip
      service: light.turn_on