light:
  - platform: group
    name: Backyard Lights
    entities:
      - light.backyard_light_light

camera:
  - platform: generic
    name: backyard
    still_image_url: https://home.adebenham.com/int/motion/picture/6/current/
    stream_source: rtsp://dafang.lan:8554/unicast

automation:
  - alias: Backyard - Backdoors left open
    trigger:
      - platform: state
        entity_id: binary_sensor.backdoor_sensor_contact
        for: "0:05:00"
        to: 'on'
      - platform: state
        entity_id: binary_sensor.back_screen_door_contact
        for: "0:05:00"
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.backdoor_sensor_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.back_screen_door_contact
          state: 'on'
    action:
      - service: notify.hangout_notify
        data:
          message: "Back doors left open"
      - service: notify.google_assistant
        data:
          message: "Heads up - Someone left the back doors open"
  - alias: Backyard - Backyard light - night on
    trigger: 
      - platform: state
        entity_id: binary_sensor.backdoor_sensor_contact
        to: 'Open'
    condition:
      condition: or
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"
        - condition: sun
          before: sunrise
          before_offset: "-01:00:00"
    action:
      service: light.turn_on
      data:
        entity_id: light.backyard_lights
  - alias: Backyard - Backyard light - night on
    trigger:
      - platform: state
        entity_id:  binary_sensor.backdoor_sensor_contact
        to: 'Closed'
        for:
          minutes: 5
    condition: []
    action:
      service: light.turn_off
      data:
        entity_id:  light.sensor_light
  - alias: Backyard - Backdoor switch on
    trigger:
      - platform: state
        entity_id: light.backyard_lights
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        data:
          entity_id: light.backyard_lights
          brightness_pct: 100
