light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedrooma
      - light.bedroomb

switch:
  - platform: template
    switches:
      bedroom_lights:
        value_template: "{{ states('light.bedroom_lights') }}"
        icon_template: mdi:bed-empty
        friendly_name: "Bedroom"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.bedroom_lights
              brightness_pct: 100
              color_temp: 370
              transition: 1
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.bedroom_lights
              transition: 1

climate:
  - platform: generic_thermostat
    name: Main Bedroom
    heater: switch.bedroom_heater
    target_sensor: sensor.bedroom_temperature
    initial_hvac_mode: "off"

automation:
  - id: kids_lights
    alias: Main bedroom - Kid indicator
    trigger:
      - platform: state
        entity_id: light.lucas
      - platform: state
        entity_id: light.xander_bedroom_light
    condition: []
    action:
      service: light.turn_on
      data_template:
        entity_id: light.bedroom_led
        brightness_pct: "{% if is_state('light.lucas', 'off') and is_state('light.xander_bedroom_light_light', 'off') %}0{% else %}40{% endif %}"
        color_name: >
          {% if is_state('light.lucas', 'on') and is_state('light.xander_bedroom_light_light', 'on') %} red
          {% elif is_state('light.lucas', 'off') and is_state('light.xander_bedroom_light_light', 'on') %} green
          {% elif is_state('light.lucas', 'on') and is_state('light.xander_bedroom_light_light', 'off') %} blue
          {% else %} white
          {% endif %}
  - id: main_bedroom_night_mode
    alias: Main bedroom night mode
    trigger:
      platform: time
      at: '20:30:00'
    condition:
      condition: state
      entity_id: light.bedroom_lights
      state: 'off'
    action:
      service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 125
        white_value: 125
        transition: 300
        color_temp: 370
  - alias: Dimmer - Main Bedroom
    trigger:
    - entity_id: sensor.bedroom_dimmer_action
      platform: state
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state in ['on-press', 'up-press', 'down-press', 'off-press'] }}"
    action:
    - entity_id: light.bedroom_lights
      service: light.turn_on
      data_template:
        transition: 1
        brightness: 1
        color_temp: 370
        white_value: >
          {% if trigger.to_state.state == 'on-press' %} 255
          {% elif trigger.to_state.state == 'up-press' %} 125
          {% elif trigger.to_state.state == 'down-press' %} 30
          {% elif trigger.to_state.state == 'off-press' %} 0
          {% endif %}
    - entity_id: switch.bedroom_relay_1
      service: switch.turn_on
  - alias: Main Bedroom - Switch1
    trigger:
    - entity_id: binary_sensor.bedroom_switch1
      platform: state
      to: 'on'
    action:
    - entity_id: light.bedroom_lights
      service: light.turn_on
      data:
        transition: 1
        brightness: 255
        white_value: 255
        color_temp: 370
    - entity_id: switch.bedroom_relay_1
      service: switch.turn_on
  - alias: Main Bedroom - Switch2
    trigger:
    - entity_id: binary_sensor.bedroom_switch2
      platform: state
      to: 'on'
    action:
    - entity_id: light.bedroom_lights
      service: light.turn_on
      data:
        transition: 1
        brightness: 125
        color_temp: 370
        white_value: 125
    - entity_id: switch.bedroom_relay_1
      service: switch.turn_on
  - alias: Main Bedroom - Switch3
    trigger:
    - entity_id: binary_sensor.bedroom_switch3
      platform: state
      to: 'on'
    action:
    - entity_id: light.bedroom_lights
      service: light.turn_off
      data:
        transition: 1
