light:
  - platform: group
    name: Bedroom Lights
    entities:
      - light.bedrooma
      - light.bedroomb

switch:
  - platform: template
    switches:
      bedroom_lights:
        value_template: "{{ states('light.bedroom_lights') }}"
        icon_template: mdi:bed-empty
        friendly_name: "Bedroom"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.bedroom_lights
              brightness_pct: 100
              color_temp: 370
              transition: 1
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.bedroom_lights
              transition: 1

climate:
  - platform: generic_thermostat
    name: Main Bedroom
    heater: switch.bedroom_heater
    target_sensor: sensor.bedroom_temperature
    initial_hvac_mode: "off"

automation:
  - id: kids_lights
    alias: Main bedroom - Kid indicator
    trigger:
      - platform: state
        entity_id: light.lucas_lights
      - platform: state
        entity_id: light.xander_lights
    condition: []
    action:
      service: light.turn_on
      data_template:
        entity_id: light.bedroom_led
        brightness_pct: "{% if is_state('light.lucas_lights', 'off') and is_state('light.xander_lights', 'off') %}0{% else %}40{% endif %}"
        color_name: >
          {% if is_state('light.lucas_lights', 'on') and is_state('light.xander_lights', 'on') %} red
          {% elif is_state('light.lucas_lights', 'off') and is_state('light.xander_lights', 'on') %} green
          {% elif is_state('light.lucas_lights', 'on') and is_state('light.xander_lights', 'off') %} blue
          {% else %} white
          {% endif %}
  - id: main_bedroom_night_mode
    alias: Main bedroom - night mode
    trigger:
      platform: time
      at: '20:30:00'
    condition:
      condition: state
      entity_id: light.bedroom_lights
      state: 'off'
    action:
      service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 125
        transition: 300
        color_temp: 450
  - alias: Main Bedroom - Dimmer
    trigger:
    - entity_id: sensor.bedroom_dimmer_action
      platform: state
      to: 'down-press'
    action:
    - entity_id: light.bedroom_lights
      service: light.turn_on
      data_template:
        transition: 1
        color_name: blue
        brightness: 80
    - entity_id: switch.bedroom_relay_1
      service: switch.turn_on