light:
  - platform: switch
    name: Carport Lights
    entity_id:
      - switch.carport

camera:
  - platform: generic
    name: carport
    still_image_url: https://home.adebenham.com/int/motion/picture/1/current/
    stream_source: rtsp://admin:542285@192.168.86.42/live/profile.0

binary_sensor:
  - platform: mqtt
    state_topic: "home/carport/camera/motion"
    name: Carport Camera Motion
    device_class: motion

switch:
  - platform: template
    switches:
      front_lights:
        value_template: "{{ states('light.carport_lights') }}"
        icon_template: mdi:car
        friendly_name: "Front"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.carport_lights
              brightness_pct: 100
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.carport_lights

automation:
  - alias: Carport - motion
    trigger:
      - platform: state
        entity_id: binary_sensor.carport_camera_motion
        to: 'on'
    condition: []
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.carport
          filename: /config/www/camera-snapshots/carport.jpg
      - service: notify.mobile_app_chrisphone
        data:
          message: "Carport motion"
          data:
            image: "https://ha.adebenham.com/local/camera-snapshots/carport.jpg"
      - service: image_processing.scan
        entity_id: image_processing.doods_camera_carport
