light:
  - platform: switch
    name: Carport Lights
    entity_id:
      - switch.carport

camera:
  - platform: reolink_dev
    name: entry
    host: 192.168.86.199
    username: admin
    password: ""
  - platform: reolink_dev
    name: carport
    host: 192.168.86.130
    username: admin
    password: ""

binary_sensor:
  - platform: mqtt
    state_topic: "home/carport/camera/motion"
    name: Carport Camera Motion
    device_class: motion
  - platform: template
    sensors:
      motion_entry:
        friendly_name: Camera Entry
        device_class: motion
        entity_id: camera.entry
        value_template: "{{ is_state('camera.entry', 'motion') }}"
        delay_off:
          seconds: 30
  - platform: template
    sensors:
      motion_entry:
        friendly_name: Camera Carport
        device_class: motion
        entity_id: camera.carport
        value_template: "{{ is_state('camera.carport', 'motion') }}"
        delay_off:
          seconds: 30

switch:
  - platform: template
    switches:
      front_lights:
        value_template: "{{ states('light.carport_lights') }}"
        icon_template: mdi:car
        friendly_name: "Front"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.carport_lights
              brightness_pct: 100
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.carport_lights
      camera_entry_ir_lights:
        value_template: "{{ is_state_attr('camera.entry', 'ir_lights_enabled', true) }}"
        turn_on:
          service: camera.enable_ir_lights
          data:
            entity_id: camera.entry
        turn_off:
          service: camera.disable_ir_lights
          data:
            entity_id: camera.entry
        icon_template: >-
          {% if is_state_attr('camera.entry', 'ir_lights_enabled', true) %}
            mdi:flashlight
          {% else %}
            mdi:flashlight-off
          {% endif %}
      camera_carport_ir_lights:
        value_template: "{{ is_state_attr('camera.carport', 'ir_lights_enabled', true) }}"
        turn_on:
          service: camera.enable_ir_lights
          data:
            entity_id: camera.carport
        turn_off:
          service: camera.disable_ir_lights
          data:
            entity_id: camera.carport
        icon_template: >-
          {% if is_state_attr('camera.carport', 'ir_lights_enabled', true) %}
            mdi:flashlight
          {% else %}
            mdi:flashlight-off
          {% endif %}

automation:
  - alias: Carport - motion
    trigger:
      - platform: state
        entity_id: binary_sensor.carport_camera_motion
        to: 'on'
    condition: []
    action:
      - service: camera.snapshot
        data:
          entity_id: camera.carport
          filename: /config/www/camera-snapshots/carport.jpg
      - service: notify.mobile_app_chrisphone
        data:
          message: "Carport motion"
          data:
            image: "https://ha.adebenham.com/local/camera-snapshots/carport.jpg"
      - service: image_processing.scan
        entity_id: image_processing.doods_camera_carport
