light:
  - platform: switch
    name: Carport Lights
    entity_id:
      - switch.entry_relay_1


entity_controller:
  entry_motion_light:
    sensor:
      - binary_sensor.carport_motion
      - binary_sensor.entrycam_motion
      - sensor.carport_camera_motion
      - sensor.entry_camera_motion
    entity: light.carport_lights
    delay: 180
    start_time: sunset - 00:30:00
    end_time: sunrise + 00:30:00

binary_sensor:
  - platform: template
    sensors:
      motion_entry:
        friendly_name: Camera Entry
        device_class: motion
        value_template: "{{ is_state('camera.entry_reo', 'motion') }}"
        delay_off: 
          seconds: 30
  - platform: template
    sensors:
      motion_carport:
        friendly_name: Camera Carport
        device_class: motion
        value_template: "{{ is_state('camera.carport_reo', 'motion') }}"
        delay_off: 
          seconds: 30

#sensor:
#  - platform: mqtt
#    state_topic: "zoneminder/2"
#    name: Carport Camera Motion
#    value_template: '{% if value_json.state == "alarm" %} on {% else %} off {% endif %}'
#  - platform: mqtt
#    state_topic: "zoneminder/7"
#    name: Entry Camera Motion
#    value_template: '{% if value_json.state == "alarm" %} on {% else %} off {% endif %}'

switch:
  - platform: template
    switches:
      front_lights:
        value_template: "{{ states('light.carport_lights') }}"
        icon_template: mdi:car
        friendly_name: "Front"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.carport_lights
              brightness: 255
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.carport_lights
  - platform: telnet
    switches:
      zm_trigger_carport:
        resource: 'dock'
        port: 6802
        command_on: '1|on|123|Motion Trigger|Home Assistant'
        command_off: '1|off|123|Motion Trigger|Home Assistant'
      zm_trigger_entry:
        resource: 'dock'
        port: 6802
        command_on: '2|on|123|Motion Trigger|Home Assistant'
        command_off: '2|off|123|Motion Trigger|Home Assistant'

automation:
  - alias: Carport - motion
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_carport
          - binary_sensor.motion_entry
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: light.carport_lights
      state: 'off'
      for:
        seconds: 5
    action:
      - service: light.turn_on
        entity_id: light.carport_lights
      - service: switch.turn_on
        entity_id: switch.zm_trigger_carport
      - service: switch.turn_on
        entity_id: switch.zm_trigger_entry
  - alias: Carport - motion off
    mode: restart
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_carport
          - binary_sensor.motion_entry
        from: 'on'
        to: 'off'
    condition: []
    action:
      - service: switch.turn_off
        entity_id: switch.zm_trigger_entry
      - service: switch.turn_off
        entity_id: switch.zm_trigger_carport
      - delay: 00:01:00
      - service: light.turn_off
        entity_id: light.carport_lights
