light:
  - platform: group
    name: Craftroom Lights
    entities:
      - light.craft_room

switch:
  - platform: template
    switches:
      craftroom_lights:
        icon_template: mdi:content-cut
        friendly_name: "Craft"
        value_template: "{{ states('light.craftroom_lights') }}"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.craftroom_lights
              brightness_pct: 100
              color_temp: 370
              transition: 1
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.craftroom_lights
              transition: 1

automation:
  - alias: Dimmer - Craftroom
    trigger:
    - entity_id: sensor.craftroom_dimmer_action
      platform: state
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state in ['on-press', 'up-press', 'down-press', 'off-press'] }}"
    action:
    - entity_id: light.craftroom_lights
      service: light.turn_on
      data_template:
        color_temp: 370
        brightness_pct: >
          {% if trigger.to_state.state == 'on-press' %} 100
          {% elif trigger.to_state.state == 'up-press' %} 50
          {% elif trigger.to_state.state == 'down-press' %} 1
          {% elif trigger.to_state.state == 'off-press' %} 0
          {% endif %}
