sensor:
  - platform: deluge
    host: 192.168.0.9
    username: cjd
    password: cjd
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'

switch:
  - platform: deluge
    host: 192.168.0.9
    username: cjd
    password: cjd