input_boolean:
  night_mode:
    name: Night Mode
    initial: false

automation:
  - id: '1620862005728'
    alias: Night Mode - turn on
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.entry_sensor_illuminance_lux
        below: 200
        for: "00:05:00"
      - platform: time
        at: "18:30:00"
      - platform: sun
        event: sunset
    condition: []
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.night_mode
    mode: single
  - id: '1620862057648'
    alias: Night Mode - turn off
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.entry_sensor_illuminance_lux
        above: 200
        for: "00:15:00"
      - platform: time
        at: "06:30:00"
      - platform: sun
        event: sunrise
    condition: []
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode
    mode: single
