light:
  - platform: group
    name: Hall Lights
    entities:
      - light.hallbulb

switch:
  - platform: template
    switches:
      hall_lights:
        value_template: "{{ states('light.hall_lights') }}"
        friendly_name: "Hall"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.hall_lights
              brightness_pct: 100
              color_name: white
              transition: 1
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.hall_lights
              transition: 1

automation:
  # Change the hall light colour based on time and if the kids lights are on
  - id: hall_nightlight
    alias: Hall - nightlight
    trigger:
      platform: sun
      event: sunset
      offset: "-00:45:00"
    condition: []
    action:
    - service: light.turn_on
      data:
        entity_id: light.hall_lights
        transition: 0
        brightness_pct: 50
        white_value: 120
        color_name: white
  - id: hall_morning
    alias: Hall - morning
    trigger:
      platform: sun
      event: sunrise
    condition: []
    action:
    - service: light.turn_off
      data:
        entity_id: light.hall_lights
  - id: hall_kidslightson
    alias: Hall - Kids lights on
    trigger:
      - platform: state
        entity_id: light.xander_lights
        to: 'on'
        for: 0:00:03
    condition:
      condition: and
      conditions:
        - condition: time
          after: '19:00:00'
          before: '06:00:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hall_lights
          transition: 0
          brightness_pct: 50
          white_value: 120
          color_name: white
  - id: hall_kidslightsoff
    alias: Hall - Kids lights off
    trigger:
      - platform: state
        entity_id: light.xander_lights
        to: 'off'
        for: 0:00:03
    condition:
      condition: and
      conditions:
        - condition: time
          after: '19:00:00'
          before: '06:00:00'
    action:
      - service: light.turn_on
        data:
          entity_id: light.hall_lights
          transition: 0
          color_name: blue
          brightness_pct: 30
