light:
  - platform: group
    name: Kitchen Lights
    entities:
      - light.kitchen_back
      - light.kitchen_front
      - light.kitchen_counter_light

switch:
  - platform: template
    switches:
      kitchen_lights:
        icon_template: mdi:fridge
        friendly_name: "Kitchen"
        value_template: "{{ states('light.kitchen_lights') }}"
        turn_on:
          service: light.turn_on
          data:
              entity_id: light.kitchen_lights
              brightness_pct: 100
              transition: 1
              color_temp: 420
        turn_off:
          service: light.turn_off
          data:
              entity_id: light.kitchen_lights
              transition: 1

fan:
  - platform: template
    fans:
      kitchen_fan:
        friendly_name: "Kitchen Fan"
        value_template: "{{ states('switch.kitchen_relay_3.state') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.kitchen_relay_3
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.kitchen_relay_3

automation:
  - alias: Kitchen - Switch1
    trigger:
    - entity_id: binary_sensor.kitchen_switch1
      platform: state
      to: 'on'
    condition: []
    action:
    - entity_id: switch.kitchen_relay_1
      service: switch.turn_on
    - entity_id: light.kitchen_lights
      service: light.turn_on
      data:
        transition: 1
        brightness_pct: 100
        color_temp: 420
  - alias: Kitchen - Switch2
    trigger:
    - entity_id: binary_sensor.kitchen_switch2
      platform: state
      to: 'on'
    condition: []
    action:
    - entity_id: switch.kitchen_relay_1
      service: switch.turn_on
    - entity_id: light.kitchen_lights
      service: light.turn_on
      data:
        transition: 1
        brightness_pct: 40
        color_temp: 420
  - alias: Kitchen - Switch3
    trigger:
    - entity_id: binary_sensor.kitchen_switch3
      platform: state
      to: 'on'
    condition: []
    action:
    - entity_id: light.kitchen_lights
      service: light.turn_off
      data:
        transition: 1
