light:
  - platform: group
    name: Livingroom Lights
    entities:
      - light.livingroomside
      - light.livingrooma
      - light.livingroomb

switch:
  - platform: template
    switches:
      livingroom_lights:
        icon_template: mdi:sofa
        friendly_name: "Livingroom"
        value_template: "{{ states('light.livingroom_lights') }}"
        turn_on:
          service: scene.turn_on
          entity_id: scene.normal
        turn_off:
          service: scene.turn_on
          entity_id: scene.turn_off

climate:
  - platform: sensibo
    api_key: !secret sensibo_api_key

camera:
  - platform: ffmpeg
    name: livingroom
    input: rtsp://livingcam.lan:554/

automation:
  - alias: Livingroom - Switch 1
    trigger:
      - entity_id: binary_sensor.livingroom_switch1
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - entity_id: scene.normal
        service: scene.turn_on
  - alias: Livingroom - Switch 2
    trigger:
      - entity_id: binary_sensor.livingroom_switch2
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - entity_id: scene.night
        service: scene.turn_on
  - alias: Livingroom - Switch 2 - longpress
    trigger:
      - entity_id: binary_sensor.livingroom_switch2
        platform: state
        from: 'off'
        to: 'on'
        for: "00:00:05"
    condition: []
    action:
      - entity_id: scene.party
        service: scene.turn_on
  - alias: Livingroom - Switch 3
    trigger:
      - entity_id: binary_sensor.livingroom_switch3
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - entity_id: scene.turn_off
        service: scene.turn_on
  - alias: Livingroom - AC State set
    trigger:
      - entity_id: binary_sensor.ac_active_sensor_contact
        platform: state 
        to: 'off'
        from: 'on'
        for: "00:01:00"
    condition: []
    action:
      - entity_id: climate.living_room
        service: climate.turn_off
  - alias: Livingroom - AC on but doors/windows left open
    trigger:
      - entity_id: binary_sensor.backdoor_sensor_contact
        platform: state
        from: 'off'
        to: 'on'
        for: "00:00:30"
      - entity_id: binary_sensor.frontdoor_contact
        platform: state
        from: 'off'
        to: 'on'
        for: "00:00:30"
      - entity_id: binary_sensor.livingroom_window_sensor_contact
        platform: state
        to: 'on'
        for: "00:00:30"
    condition:
      - condition: state
        entity_id: binary_sensor.ac_active_sensor_contact
        state: 'on'
    action:
      - service: notify.mobile_app_chrisphone
        data:
          title: Back door open
          message: 'The backdoor is open and the current temp is: {{states(''sensor.office_temperature'')}}'
          data:
            actions:
            - action: LIGHTS_RAINBOW
              title: Rainbow time
            - action: LIGHTS_TWINKLE
              title: Twinkle time
            - action: LIGHTS_OFF
              title: 'Off'
  - alias: Livingroom - AC on but doors/windows already open
    trigger:
      - entity_id: binary_sensor.ac_active_sensor_contact
        platform: state
        from: 'off'
        to: 'on'
        for: "00:00:30"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.backdoor_sensor_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.frontdoor_contact
          state: 'on'
        - condition: state
          entity_id: binary_sensor.livingroom_window_sensor_contact
          state: 'on'
    action:
      - service: notify.hangout_notify
        data:
          message: "AC turned on but door/window open"
  - alias: Livingroom - AC State Heat
    trigger:
      - entity_id: climate.living_room
        platform: state
        to: 'heat'
    action:
      - entity_id: input_select.livingroom_ac_state
        service: input_select.select_option
        data:
          option: "Heat"
  - alias: Livingroom - AC State Off
    trigger:
      - entity_id: climate.living_room
        platform: state
        to: 'off'
    action:
      - entity_id: input_select.livingroom_ac_state
        service: input_select.select_option
        data:
          option: 'off'
  - alias: Livingroom - AC State Fan
    trigger:
      - entity_id: climate.living_room
        platform: state
        to: 'fan_only'
    action:
      - entity_id: input_select.livingroom_ac_state
        service: input_select.select_option
        data:
          option: "Fan"
  - alias: Livingroom - AC State Dry
    trigger:
      - entity_id: climate.living_room
        platform: state
        to: 'dry'
    action:
      - entity_id: input_select.livingroom_ac_state
        service: input_select.select_option
        data:
          option: "Dry"
  - alias: Livingroom - AC State Auto
    trigger:
      - entity_id: climate.living_room
        platform: state
        to: 'heat_cool'
    action:
      - entity_id: input_select.livingroom_ac_state
        service: input_select.select_option
        data:
          option: "Auto"
  - alias: Livingroom - AC State Cool
    trigger:
      - entity_id: climate.living_room
        platform: state
        to: 'cool'
    action:
      - entity_id: input_select.livingroom_ac_state
        service: input_select.select_option
        data:
          option: "Cool"


scene:
  - name: Normal
    entities:
      light.livingroom_lights:
        state: "on"
        effect: 0
        brightness: 255
        color_temp: 420
      light.kitchen_lights:
        effect: 0
        brightness: 255
        color_temp: 420
        state: "on"
      light.kitchen_strip:
        brightness: 255
        color_name: white
        effect: None
        state: "on"
      light.tv_backlight:
        state: "on"
        brightness: 255
        effect: Slow Random Effect
      switch.livingroom_relay_1:
        state: "on"
      switch.kitchen_relay_2:
        state: "on"
  - name: Movie
    entities:
      light.livingroom_lights:
        state: "on"
        effect: 0
        brightness_pct: 50
        color_temp: 420
      light.kitchen_lights:
        effect: 0
        brightness_pct: 50
        color_temp: 420
        state: "on"
      light.kitchen_strip:
        brightness_pct: 50
        color_name: white
        effect: None
        state: "on"
      light.tv_backlight:
        state: "on"
        brightness: 255
        effect: Slow Random Effect
      switch.livingroom_relay_1:
        state: "on"
      switch.kitchen_relay_2:
        state: "on"
  - name: Night
    entities:
      light.kitchen_lights:
        state: "on"
        effect: 0
        rgb_color: [0,0,155]
        brightness: 255
      light.kitchen_strip:
        state: "on"
        effect: None
        rgb_color: [0,0,155]
        brightness: 255
      light.livingroom_lights:
        state: "on"
        effect: 0
        rgb_color: [0,0,155]
        brightness: 255
      light.backroom_lights:
        rgb_color: [0,0,155]
        effect: 0
        brightness: 255
        state: "on"
      light.tv_backlight:
        state: "on"
        brightness: 255
        effect: Random Twinkle
      switch.livingroom_relay_1:
        state: "on"
      switch.kitchen_relay_1:
        state: "on"
      switch.kitchen_relay_2:
        state: "on"
  - name: Party
    entities:
      light.kitchen_lights:
        state: "on"
        effect: 2
        rgb_color: [0,0,155]
        brightness: 255
      light.kitchen_strip:
        state: "on"
        effect: Rainbow
        brightness: 255
      light.livingroom_lights:
        state: "on"
        effect: 2
        rgb_color: [0,0,155]
        brightness: 255
      light.backroom_lights:
        state: "on"
        effect: 2
        rgb_color: [0,0,155]
        brightness: 255
      light.tv_backlight:
        state: "on"
        brightness: 255
        effect: Rainbow
      switch.livingroom_relay_1:
        state: "on"
      switch.kitchen_relay_1:
        state: "on"
      switch.kitchen_relay_2:
        state: "on"
  - name: Turn off
    entities:
      light.kitchen_lights: 
        state: "off"
      light.kitchen_strip: 
        state: "on"
        brightness: 255
        effect: Random Twinkle
      light.livingroom_lights: 
        state: "off"
      light.backroom_lights: 
        state: "off"
      light.tv_backlight:
        state: "on"
        brightness: 255
        effect: Random Twinkle
