binary_sensor:
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 1'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC088"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 2'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC08C"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 3'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC084"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 4'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC089"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 5'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC082"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 6'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC085"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 7'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC081"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 8'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "AFC083"
    off_delay: 2

automation:
  - alias: RF Remote 1
    trigger:
      - entity_id: binary_sensor.rf_button_1
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom_lights
          brightness_pct: 100
          color_temp: 450
  - alias: RF Remote 2
    trigger:
      - entity_id: binary_sensor.rf_button_2
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom_lights
          brightness_pct: 50
          color_temp: 450
  - alias: RF Remote 3
    trigger:
      - entity_id: binary_sensor.rf_button_3
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.bedroom_fan
          speed: "high"
  - alias: RF Remote 4
    trigger:
      - entity_id: binary_sensor.rf_button_4
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.bedroom_fan
          speed: "medium"
  - alias: RF Remote 5
    trigger:
      - entity_id: binary_sensor.rf_button_5
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: fan.turn_off
        data:
          entity_id: fan.bedroom_fan
  - alias: RF Remote 6
    trigger:
      - entity_id: binary_sensor.rf_button_6
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.bedroom_fan
          speed: "low"
  - alias: RF Remote 7
    trigger:
      - entity_id: binary_sensor.rf_button_7
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom_lights
          brightness_pct: 30
          color_name: blue
  - alias: RF Remote 8
    trigger:
      - entity_id: binary_sensor.rf_button_8
        platform: state
        from: 'off'
        to: 'on'
    condition: []
    action:
      - service: light.turn_off
        data:
          entity_id: light.bedroom_lights
