sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: last_boot
      - type: disk_free
        arg: /
  - platform: pfsense_gateways
    host: 192.168.86.1
    name: pfSense gateway
    key: pfsense
    monitored_gateway_interfaces:
      - wan
