binary_sensor:
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 1'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "361F01"
    off_delay: 2
  - platform: mqtt
    state_topic: "SonoffRF/tele/RESULT"
    name: 'RF Button 2'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: "B12201"
    off_delay: 2
