automation:
  - alias: 'Startup - set theme'
    id: startup_actions
    initial_state: true
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: frontend.set_theme
        data:
          name: "yourname"
      - service: mqtt.publish
        data:
          topic: "tasmotas/cmnd/state"
          payload: ""
      - service: mqtt.publish
        data:
          topic: "cmnd/LoungeroomBlind/shutterposition"
          payload: ""        
      - service: mqtt.publish
        data:
          topic: "cmnd/LoungeroomBlind/serialsend5"
          payload: "55aa0001000000"
      - service: tts.google_translate_say
        data:
          entity_id: media_player.office_speaker_2
          message: Home Assistant Started