sensor:
  - platform: template
    sensors:
      bom_current_text:
        value_template: >
            {% set val = states('sensor.narara_short_text_0').split('.')[0] %} 
            {{ val | title }}

      bom_uv_alert:
        value_template: >
            UV Today: Sun Protection 
            {{ as_timestamp(states('sensor.narara_uv_start_time_0')) | timestamp_custom(' %I:%M%p') | lower | replace(" 0", "") }} to {{ as_timestamp(states('sensor.narara_uv_end_time_0')) | timestamp_custom(' %I:%M%p') | lower | replace(" 0", "") }}, UV Index predicted to reach {{ states('sensor.narara_uv_max_index_0') }} [{{ states('sensor.narara_uv_category_0') }}]

      bom_fire_danger:
        value_template: "Fire Danger Today: {{ states('sensor.narara_fire_danger_0') }}"

      bom_forecast_0:
        friendly_name: "Today"
        value_template: >
          {% if states('sensor.narara_temp_min_0') == 'unknown' %} {% set min = states('sensor.bom_today_min') %} {% else %} {% set min = states('sensor.narara_temp_min_0') %} {% endif %}
          {% if states('sensor.narara_temp_max_0') == 'unknown' %} {% set max = states('sensor.bom_today_max') %} {% else %} {% set max = states('sensor.narara_temp_max_0') %} {% endif %}
          {{ max|round(0)}}°/{{ min|round(0)}}°/{{states('sensor.narara_rain_chance_0')|round(0)}}%
        entity_picture_template: >-
          {%- if states('sun.sun') == 'below_horizon' and (states('sensor.narara_icon_descriptor_0') == 'fog' or states('sensor.narara_icon_descriptor_0') == 'haze' or states('sensor.narara_icon_descriptor_0') == 'light-showers' or states('sensor.narara_icon_descriptor_0') == 'partly-cloudy' or states('sensor.narara_icon_descriptor_0') == 'showers' or  states('sensor.narara_icon_descriptor_0') == 'light_shower' or states('sensor.narara_icon_descriptor_0') == 'shower' or states('sensor.narara_icon_descriptor_0') == 'light_showers' or states('sensor.narara_icon_descriptor_0') == 'partly_cloudy') -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_0') ~ '-night.png' }}
          {%- else -%}
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_0') ~ '.png' }}
          {%- endif -%}

      bom_forecast_1:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (1 * 86400 ) -%}
          {{ date | timestamp_custom('Tomorrow (%-d/%-m)') }}
        value_template: >
          {{states('sensor.narara_temp_max_1')|round(0)}}°/{{states('sensor.narara_temp_min_1')|round(0)}}°/{{states('sensor.narara_rain_chance_1')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_1') ~ '.png' }}

      bom_forecast_2:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (2 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.narara_temp_max_2')|round(0)}}°/{{states('sensor.narara_temp_min_2')|round(0)}}°/{{states('sensor.narara_rain_chance_2')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_2') ~ '.png' }}

      bom_forecast_3:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (3 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.narara_temp_max_3')|round(0)}}°/{{states('sensor.narara_temp_min_3')|round(0)}}°/{{states('sensor.narara_rain_chance_3')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_3') ~ '.png' }}

      bom_forecast_4:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (4 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.narara_temp_max_4')|round(0)}}°/{{states('sensor.narara_temp_min_4')|round(0)}}°/{{states('sensor.narara_rain_chance_4')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_4') ~ '.png' }}

      bom_forecast_5:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (5 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.narara_temp_max_5')|round(0)}}°/{{states('sensor.narara_temp_min_5')|round(0)}}°/{{states('sensor.narara_rain_chance_5')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_5') ~ '.png' }}

      bom_forecast_6:
        friendly_name_template: >
          {%- set date = as_timestamp(now()) + (6 * 86400 ) -%}
          {{ date | timestamp_custom('%A (%-d/%-m)') }}
        value_template: >
          {{states('sensor.narara_temp_max_6')|round(0)}}°/{{states('sensor.narara_temp_min_6')|round(0)}}°/{{states('sensor.narara_rain_chance_6')|round(0)}}%
        entity_picture_template: >-
          {{ '/local/icons/bom_icons/' ~ states('sensor.narara_icon_descriptor_6') ~ '.png' }}


      bom_today_max:
        value_template: >
          {{ state_attr('sensor.today_temp_bom', 'max_value') }}

      bom_today_min:
        value_template: >
          {{ state_attr('sensor.today_temp_bom', 'min_value') }}

  - platform: average
    name: today_temp_bom
    entities:
      - sensor.gosford_temp
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
