zoneminder:
  - host: 192.168.86.2:6080
    username: !secret zoneminder_username
    password: !secret zoneminder_password
camera:
  - platform: zoneminder
sensor:
  - platform: zoneminder
    include_archived: false
